# TP - Work with text data
---

## Imports

In [19]:
import pandas as pd

## Load data

In [20]:
data = pd.read_csv("scrapping_and_api_data_only_description.csv",
                   header=None, names=['description'])
df = data

In [21]:
data.head()

                                         description
0  Paolo Rumiz, né le 20 décembre 1947 à Trieste,...
1  Saverio Tomasella est un psychanalyste et écri...
2  Annelise Heurtier, née en 1979 à Villefranche-...
3  Erik Orsenna, pseudonyme d’Éric Arnoult, est u...
4  Christophe Tison est un journaliste et écrivai...

## Feature extraction

### Number of words

In [24]:
df['description'][0]

'Paolo Rumiz, né le 20 décembre 1947 à Trieste, est un journaliste et un écrivain voyageur italien.'

In [25]:
df['description'].apply(lambda x: len(x.split(' ')))

0       17
1       15
2       16
3       20
4       13
      ...
134     37
135     27
136     20
137    174
138    617
Name: description, Length: 139, dtype: int64

In [22]:
df['wordCount'] = df['description'].apply(lambda x: len(x.split(' ')))
df.head()

                                         description  wordCount
0  Paolo Rumiz, né le 20 décembre 1947 à Trieste,...         17
1  Saverio Tomasella est un psychanalyste et écri...         15
2  Annelise Heurtier, née en 1979 à Villefranche-...         16
3  Erik Orsenna, pseudonyme d’Éric Arnoult, est u...         20
4  Christophe Tison est un journaliste et écrivai...         13

Or another method

In [11]:
df['wordCount'] = df['description'].str.split().str.len()
df.head()

                                         description  wordCount
0  Paolo Rumiz, né le 20 décembre 1947 à Trieste,...         17
1  Saverio Tomasella est un psychanalyste et écri...         15
2  Annelise Heurtier, née en 1979 à Villefranche-...         16
3  Erik Orsenna, pseudonyme d’Éric Arnoult, est u...         21
4  Christophe Tison est un journaliste et écrivai...         13

### Number of  characters

In [23]:
df['characterCount'] = df['description'].str.len()

In [29]:
df.head()

,description,wordCount,characterCount
0,"Paolo Rumiz, né le 20 décembre 1947 à Trieste,...",17,98
1,Saverio Tomasella est un psychanalyste et écri...,15,96
2,"Annelise Heurtier, née en 1979 à Villefranche-...",16,122
3,"Erik Orsenna, pseudonyme d’Éric Arnoult, est u...",20,125
4,Christophe Tison est un journaliste et écrivai...,13,77

### Number of numerics

**Tips:** 
- Use `isdigit` function

In [50]:
df['description'].apply(lambda x: sum(c.isdigit() for c in x.split(' ')))

0      2
1      1
2      1
3      2
4      0
      ..
134    4
135    2
136    2
137    3
138    8
Name: description, Length: 139, dtype: int64

In [46]:
df['description'].apply(lambda x: sum(c.isdigit() for c in x)) #checks for every character in the string

0       6
1       6
2       4
3       6
4       4
       ..
134    13
135     6
136     5
137    15
138    39
Name: description, Length: 139, dtype: int64

In [54]:
df['description'].apply(lambda x: [w.isdigit() for w in x.split(' ')])

0      [False, False, False, False, True, False, True...
1      [False, False, False, False, False, False, Fal...
2      [False, False, False, False, True, False, Fals...
3      [False, False, False, False, False, False, Fal...
4      [False, False, False, False, False, False, Fal...
                             ...
134    [False, False, False, False, False, False, Fal...
135    [False, False, False, False, True, False, True...
136    [False, False, False, False, True, False, True...
137    [False, False, False, False, False, False, Fal...
138    [False, False, False, False, False, False, Fal...
Name: description, Length: 139, dtype: object

In [24]:
df['numericCount'] = df['description'].apply(lambda x: sum(w.isdigit() for w in x.split(' ')))
df.head()

,description,wordCount,characterCount,numericCount
0,"Paolo Rumiz, né le 20 décembre 1947 à Trieste,...",17,98,2
1,Saverio Tomasella est un psychanalyste et écri...,15,96,1
2,"Annelise Heurtier, née en 1979 à Villefranche-...",16,122,1
3,"Erik Orsenna, pseudonyme d’Éric Arnoult, est u...",20,125,2
4,Christophe Tison est un journaliste et écrivai...,13,77,0

### Number of Uppercase words

In [25]:
df['isUpperCase'] = df['description'].apply(lambda x: sum(w.isupper() for w in x.split(' ')))
df

,description,wordCount,characterCount,numericCount,isUpperCase
0,"Paolo Rumiz, né le 20 décembre 1947 à Trieste,...",17,98,2,0
1,Saverio Tomasella est un psychanalyste et écri...,15,96,1,0
2,"Annelise Heurtier, née en 1979 à Villefranche-...",16,122,1,0
3,"Erik Orsenna, pseudonyme d’Éric Arnoult, est u...",20,125,2,0
4,Christophe Tison est un journaliste et écrivai...,13,77,0,0
5,"Sylvain Prudhomme, né en 1979 à La Seyne-sur-M...",32,201,1,0
6,Sally Nicholls (née le 22 juin 1983 à Stockton...,19,121,2,0
7,"Maxime Drouot, connu sous les pseudonymes de M...",38,235,2,0
8,"Ivan Jablonka, né le 23 octobre 1973 à Paris, ...",21,147,2,0
9,"Jean-Pierre Cabanes, né le 31 juillet 1949 à M...",15,93,2,0
10,Alain Ayroles est un scénariste de bande dessi...,16,91,2,0
11,"Martha Wells, née le 1er septembre 1964 à Fort...",21,125,1,0
12,"Amélie Nothomb /ameli nɔtɔ̃b/, nom de plume de...",126,832,3,0
13,Florence Hinckel est une autrice française de...,13,82,0,0
14,"Karine Tuil, née le 3 mai 1972 à Paris, est un...",13,69,2,0
15,"Jérémie Kisling, né Jérémie Tschanz à Lausanne...",32,238,1,0
16,"Née le 3 janvier 1969 à Bayonne, au Pays basqu...",120,730,4,0
17,"Léonora Miano, née le 12 mars 1973 à Douala (C...",18,124,2,0
18,"Ottessa Moshfegh, née en 20 mai 1981 à Boston ...",16,98,2,0
19,"David Lagercrantz, né le 4 septembre 1962 à So...",60,352,2,0
20,"Jonathan Coe, né le 19 août 1961 à Birmingham,...",13,75,2,0
21,"Dominique Forma, né en 1962 à Puteaux, est un ...",14,99,1,0
22,"Margaret Eleanor « Peggy » Atwood, née le 18 n...",78,469,3,0
23,"Marion Brunet, née en 1976 dans le Vaucluse, e...",25,150,1,0
24,"Cécile Coulon, née le 13 juin 1990 à Clermont-...",17,123,2,0
25,"Paolo Rumiz, né le 20 décembre 1947 à Trieste,...",17,98,2,0
26,"Éléonore Pourriat est une actrice, scénariste ...",9,72,0,0
27,"Jean-Paul Dubois, né le 20 février 1950 à Toul...",13,77,2,0
28,"Jean-Baptiste Andrea, né le 4 avril 1971 à Sai...",17,119,2,0
29,Christophe Tison est un journaliste et écrivai...,13,77,0,0
...,...,...,...,...,...
109,Jean Anouilh (/a.nuj/) est un écrivain et dram...,308,1863,5,0
110,"Pierre Ambroise Choderlos de Laclos, né à Amie...",53,311,3,0
111,"Victor Hugo est un poète, dramaturge, écrivain...",406,2497,6,2
112,Anna Gavalda est une femme de lettres français...,15,95,2,0
113,"Marie-Madeleine Pioche de La Vergne, comtesse ...",34,183,4,0
114,Émile Zola est un écrivain et journaliste fran...,174,1071,3,0
115,"Jean-Baptiste Poquelin, dit Molière, est un co...",431,2711,5,1
116,Alexandre Dumas (dit aussi Alexandre Dumas pèr...,264,1674,4,1
117,Gilles Legardinier est un écrivain et scénaris...,25,142,2,0
118,"Edmond Rostand, né le 1er avril 1868 à Marseil...",61,373,3,0
119,Ernest Miller Hemingway [ˈɝnɪst ˈmɪlɚ ˈhɛmɪŋˌw...,478,2838,8,1
120,"Guillaume Musso, né le 6 juin 1974 à Antibes, ...",13,72,2,0
121,"Edgar Allan Poe [ˈɛdɡɚ ˈælən poʊ], né le 19 ja...",535,3273,7,0
122,"Jonas Jonasson, né le 6 juillet 1961 à Växjö, ...",38,214,2,0
123,"Guillaume Musso, né le 6 juin 1974 à Antibes, ...",13,72,2,0
124,"Jean Edith Camilla Läckberg Eriksson, née le 3...",92,550,2,0
125,Arthur Conan Doyle (né Arthur Ignatius Conan D...,126,740,5,1
126,"William Shakespeare, baptisé le 26 avril 1564 ...",246,1615,8,0
127,"Jean-Baptiste Poquelin, dit Molière, est un co...",431,2711,5,1
128,"Pierre Corneille, aussi appelé « le Grand Corn...",801,4790,10,5
129,"Veronica Anne Roth, née le 19 août 1988 à New ...",102,635,7,0
130,Anna Gavalda est une femme de lettres français...,15,95,2,0
131,Marguerite Duras — nom de plume de Marguerite ...,339,2098,7,1
132,Paula Hawkins (née le 26 août 1972) est une éc...,19,108,1,0
133,"J. D. Salinger, nom de plume de Jerome David S...",159,956,5,2
134,"Gaston Leroux est un romancier français, né l...",37,202,4,0
135,"Philip Pullman, né le 19 octobre 1946 à Norwic...",27,152,2,1
136,"Ken Follett, né le 5 juin 1949 à Cardiff, est ...",20,121,2,0
137,Émile Zola est un écrivain et journaliste fran...,174,1071,3,0
138,"Honoré de Balzac, né Honoré Balzac à Tours le ...",617,3880,8,2

## Text pre-processing

### Lowercase

**Tips:** 
- Use `description` column
- Use Pandas Series functions

In [26]:
df['lowercase'] = df['description'].str.lower()
df

,description,wordCount,characterCount,numericCount,isUpperCase,lowercase
0,"Paolo Rumiz, né le 20 décembre 1947 à Trieste,...",17,98,2,0,"paolo rumiz, né le 20 décembre 1947 à trieste,..."
1,Saverio Tomasella est un psychanalyste et écri...,15,96,1,0,saverio tomasella est un psychanalyste et écri...
2,"Annelise Heurtier, née en 1979 à Villefranche-...",16,122,1,0,"annelise heurtier, née en 1979 à villefranche-..."
3,"Erik Orsenna, pseudonyme d’Éric Arnoult, est u...",20,125,2,0,"erik orsenna, pseudonyme d’éric arnoult, est u..."
4,Christophe Tison est un journaliste et écrivai...,13,77,0,0,christophe tison est un journaliste et écrivai...
5,"Sylvain Prudhomme, né en 1979 à La Seyne-sur-M...",32,201,1,0,"sylvain prudhomme, né en 1979 à la seyne-sur-m..."
6,Sally Nicholls (née le 22 juin 1983 à Stockton...,19,121,2,0,sally nicholls (née le 22 juin 1983 à stockton...
7,"Maxime Drouot, connu sous les pseudonymes de M...",38,235,2,0,"maxime drouot, connu sous les pseudonymes de m..."
8,"Ivan Jablonka, né le 23 octobre 1973 à Paris, ...",21,147,2,0,"ivan jablonka, né le 23 octobre 1973 à paris, ..."
9,"Jean-Pierre Cabanes, né le 31 juillet 1949 à M...",15,93,2,0,"jean-pierre cabanes, né le 31 juillet 1949 à m..."
10,Alain Ayroles est un scénariste de bande dessi...,16,91,2,0,alain ayroles est un scénariste de bande dessi...
11,"Martha Wells, née le 1er septembre 1964 à Fort...",21,125,1,0,"martha wells, née le 1er septembre 1964 à fort..."
12,"Amélie Nothomb /ameli nɔtɔ̃b/, nom de plume de...",126,832,3,0,"amélie nothomb /ameli nɔtɔ̃b/, nom de plume de..."
13,Florence Hinckel est une autrice française de...,13,82,0,0,florence hinckel est une autrice française de...
14,"Karine Tuil, née le 3 mai 1972 à Paris, est un...",13,69,2,0,"karine tuil, née le 3 mai 1972 à paris, est un..."
15,"Jérémie Kisling, né Jérémie Tschanz à Lausanne...",32,238,1,0,"jérémie kisling, né jérémie tschanz à lausanne..."
16,"Née le 3 janvier 1969 à Bayonne, au Pays basqu...",120,730,4,0,"née le 3 janvier 1969 à bayonne, au pays basqu..."
17,"Léonora Miano, née le 12 mars 1973 à Douala (C...",18,124,2,0,"léonora miano, née le 12 mars 1973 à douala (c..."
18,"Ottessa Moshfegh, née en 20 mai 1981 à Boston ...",16,98,2,0,"ottessa moshfegh, née en 20 mai 1981 à boston ..."
19,"David Lagercrantz, né le 4 septembre 1962 à So...",60,352,2,0,"david lagercrantz, né le 4 septembre 1962 à so..."
20,"Jonathan Coe, né le 19 août 1961 à Birmingham,...",13,75,2,0,"jonathan coe, né le 19 août 1961 à birmingham,..."
21,"Dominique Forma, né en 1962 à Puteaux, est un ...",14,99,1,0,"dominique forma, né en 1962 à puteaux, est un ..."
22,"Margaret Eleanor « Peggy » Atwood, née le 18 n...",78,469,3,0,"margaret eleanor « peggy » atwood, née le 18 n..."
23,"Marion Brunet, née en 1976 dans le Vaucluse, e...",25,150,1,0,"marion brunet, née en 1976 dans le vaucluse, e..."
24,"Cécile Coulon, née le 13 juin 1990 à Clermont-...",17,123,2,0,"cécile coulon, née le 13 juin 1990 à clermont-..."
25,"Paolo Rumiz, né le 20 décembre 1947 à Trieste,...",17,98,2,0,"paolo rumiz, né le 20 décembre 1947 à trieste,..."
26,"Éléonore Pourriat est une actrice, scénariste ...",9,72,0,0,"éléonore pourriat est une actrice, scénariste ..."
27,"Jean-Paul Dubois, né le 20 février 1950 à Toul...",13,77,2,0,"jean-paul dubois, né le 20 février 1950 à toul..."
28,"Jean-Baptiste Andrea, né le 4 avril 1971 à Sai...",17,119,2,0,"jean-baptiste andrea, né le 4 avril 1971 à sai..."
29,Christophe Tison est un journaliste et écrivai...,13,77,0,0,christophe tison est un journaliste et écrivai...
...,...,...,...,...,...,...
109,Jean Anouilh (/a.nuj/) est un écrivain et dram...,308,1863,5,0,jean anouilh (/a.nuj/) est un écrivain et dram...
110,"Pierre Ambroise Choderlos de Laclos, né à Amie...",53,311,3,0,"pierre ambroise choderlos de laclos, né à amie..."
111,"Victor Hugo est un poète, dramaturge, écrivain...",406,2497,6,2,"victor hugo est un poète, dramaturge, écrivain..."
112,Anna Gavalda est une femme de lettres français...,15,95,2,0,anna gavalda est une femme de lettres français...
113,"Marie-Madeleine Pioche de La Vergne, comtesse ...",34,183,4,0,"marie-madeleine pioche de la vergne, comtesse ..."
114,Émile Zola est un écrivain et journaliste fran...,174,1071,3,0,émile zola est un écrivain et journaliste fran...
115,"Jean-Baptiste Poquelin, dit Molière, est un co...",431,2711,5,1,"jean-baptiste poquelin, dit molière, est un co..."
116,Alexandre Dumas (dit aussi Alexandre Dumas pèr...,264,1674,4,1,alexandre dumas (dit aussi alexandre dumas pèr...
117,Gilles Legardinier est un écrivain et scénaris...,25,142,2,0,gilles legardinier est un écrivain et scénaris...
118,"Edmond Rostand, né le 1er avril 1868 à Marseil...",61,373,3,0,"edmond rostand, né le 1er avril 1868 à marseil..."
119,Ernest Miller Hemingway [ˈɝnɪst ˈmɪlɚ ˈhɛmɪŋˌw...,478,2838,8,1,ernest miller hemingway [ˈɝnɪst ˈmɪlɚ ˈhɛmɪŋˌw...
120,"Guillaume Musso, né le 6 juin 1974 à Antibes, ...",13,72,2,0,"guillaume musso, né le 6 juin 1974 à antibes, ..."
121,"Edgar Allan Poe [ˈɛdɡɚ ˈælən poʊ], né le 19 ja...",535,3273,7,0,"edgar allan poe [ˈɛdɡɚ ˈælən poʊ], né le 19 ja..."
122,"Jonas Jonasson, né le 6 juillet 1961 à Växjö, ...",38,214,2,0,"jonas jonasson, né le 6 juillet 1961 à växjö, ..."
123,"Guillaume Musso, né le 6 juin 1974 à Antibes, ...",13,72,2,0,"guillaume musso, né le 6 juin 1974 à antibes, ..."
124,"Jean Edith Camilla Läckberg Eriksson, née le 3...",92,550,2,0,"jean edith camilla läckberg eriksson, née le 3..."
125,Arthur Conan Doyle (né Arthur Ignatius Conan D...,126,740,5,1,arthur conan doyle (né arthur ignatius conan d...
126,"William Shakespeare, baptisé le 26 avril 1564 ...",246,1615,8,0,"william shakespeare, baptisé le 26 avril 1564 ..."
127,"Jean-Baptiste Poquelin, dit Molière, est un co...",431,2711,5,1,"jean-baptiste poquelin, dit molière, est un co..."
128,"Pierre Corneille, aussi appelé « le Grand Corn...",801,4790,10,5,"pierre corneille, aussi appelé « le grand corn..."
129,"Veronica Anne Roth, née le 19 août 1988 à New ...",102,635,7,0,"veronica anne roth, née le 19 août 1988 à new ..."
130,Anna Gavalda est une femme de lettres français...,15,95,2,0,anna gavalda est une femme de lettres français...
131,Marguerite Duras — nom de plume de Marguerite ...,339,2098,7,1,marguerite duras — nom de plume de marguerite ...
132,Paula Hawkins (née le 26 août 1972) est une éc...,19,108,1,0,paula hawkins (née le 26 août 1972) est une éc...
133,"J. D. Salinger, nom de plume de Jerome David S...",159,956,5,2,"j. d. salinger, nom de plume de jerome david s..."
134,"Gaston Leroux est un romancier français, né l...",37,202,4,0,"gaston leroux est un romancier français, né l..."
135,"Philip Pullman, né le 19 octobre 1946 à Norwic...",27,152,2,1,"philip pullman, né le 19 octobre 1946 à norwic..."
136,"Ken Follett, né le 5 juin 1949 à Cardiff, est ...",20,121,2,0,"ken follett, né le 5 juin 1949 à cardiff, est ..."
137,Émile Zola est un écrivain et journaliste fran...,174,1071,3,0,émile zola est un écrivain et journaliste fran...
138,"Honoré de Balzac, né Honoré Balzac à Tours le ...",617,3880,8,2,"honoré de balzac, né honoré balzac à tours le ..."

### Replace Line Return (\n) by whitespace

** Tips :** Use `lowercase` column

In [27]:
df['withoutLineReturn'] = df['lowercase'].str.replace('\n',' ')
df

,description,wordCount,characterCount,numericCount,isUpperCase,lowercase,withoutLineReturn
0,"Paolo Rumiz, né le 20 décembre 1947 à Trieste,...",17,98,2,0,"paolo rumiz, né le 20 décembre 1947 à trieste,...","paolo rumiz, né le 20 décembre 1947 à trieste,..."
1,Saverio Tomasella est un psychanalyste et écri...,15,96,1,0,saverio tomasella est un psychanalyste et écri...,saverio tomasella est un psychanalyste et écri...
2,"Annelise Heurtier, née en 1979 à Villefranche-...",16,122,1,0,"annelise heurtier, née en 1979 à villefranche-...","annelise heurtier, née en 1979 à villefranche-..."
3,"Erik Orsenna, pseudonyme d’Éric Arnoult, est u...",20,125,2,0,"erik orsenna, pseudonyme d’éric arnoult, est u...","erik orsenna, pseudonyme d’éric arnoult, est u..."
4,Christophe Tison est un journaliste et écrivai...,13,77,0,0,christophe tison est un journaliste et écrivai...,christophe tison est un journaliste et écrivai...
5,"Sylvain Prudhomme, né en 1979 à La Seyne-sur-M...",32,201,1,0,"sylvain prudhomme, né en 1979 à la seyne-sur-m...","sylvain prudhomme, né en 1979 à la seyne-sur-m..."
6,Sally Nicholls (née le 22 juin 1983 à Stockton...,19,121,2,0,sally nicholls (née le 22 juin 1983 à stockton...,sally nicholls (née le 22 juin 1983 à stockton...
7,"Maxime Drouot, connu sous les pseudonymes de M...",38,235,2,0,"maxime drouot, connu sous les pseudonymes de m...","maxime drouot, connu sous les pseudonymes de m..."
8,"Ivan Jablonka, né le 23 octobre 1973 à Paris, ...",21,147,2,0,"ivan jablonka, né le 23 octobre 1973 à paris, ...","ivan jablonka, né le 23 octobre 1973 à paris, ..."
9,"Jean-Pierre Cabanes, né le 31 juillet 1949 à M...",15,93,2,0,"jean-pierre cabanes, né le 31 juillet 1949 à m...","jean-pierre cabanes, né le 31 juillet 1949 à m..."
10,Alain Ayroles est un scénariste de bande dessi...,16,91,2,0,alain ayroles est un scénariste de bande dessi...,alain ayroles est un scénariste de bande dessi...
11,"Martha Wells, née le 1er septembre 1964 à Fort...",21,125,1,0,"martha wells, née le 1er septembre 1964 à fort...","martha wells, née le 1er septembre 1964 à fort..."
12,"Amélie Nothomb /ameli nɔtɔ̃b/, nom de plume de...",126,832,3,0,"amélie nothomb /ameli nɔtɔ̃b/, nom de plume de...","amélie nothomb /ameli nɔtɔ̃b/, nom de plume de..."
13,Florence Hinckel est une autrice française de...,13,82,0,0,florence hinckel est une autrice française de...,florence hinckel est une autrice française de...
14,"Karine Tuil, née le 3 mai 1972 à Paris, est un...",13,69,2,0,"karine tuil, née le 3 mai 1972 à paris, est un...","karine tuil, née le 3 mai 1972 à paris, est un..."
15,"Jérémie Kisling, né Jérémie Tschanz à Lausanne...",32,238,1,0,"jérémie kisling, né jérémie tschanz à lausanne...","jérémie kisling, né jérémie tschanz à lausanne..."
16,"Née le 3 janvier 1969 à Bayonne, au Pays basqu...",120,730,4,0,"née le 3 janvier 1969 à bayonne, au pays basqu...","née le 3 janvier 1969 à bayonne, au pays basqu..."
17,"Léonora Miano, née le 12 mars 1973 à Douala (C...",18,124,2,0,"léonora miano, née le 12 mars 1973 à douala (c...","léonora miano, née le 12 mars 1973 à douala (c..."
18,"Ottessa Moshfegh, née en 20 mai 1981 à Boston ...",16,98,2,0,"ottessa moshfegh, née en 20 mai 1981 à boston ...","ottessa moshfegh, née en 20 mai 1981 à boston ..."
19,"David Lagercrantz, né le 4 septembre 1962 à So...",60,352,2,0,"david lagercrantz, né le 4 septembre 1962 à so...","david lagercrantz, né le 4 septembre 1962 à so..."
20,"Jonathan Coe, né le 19 août 1961 à Birmingham,...",13,75,2,0,"jonathan coe, né le 19 août 1961 à birmingham,...","jonathan coe, né le 19 août 1961 à birmingham,..."
21,"Dominique Forma, né en 1962 à Puteaux, est un ...",14,99,1,0,"dominique forma, né en 1962 à puteaux, est un ...","dominique forma, né en 1962 à puteaux, est un ..."
22,"Margaret Eleanor « Peggy » Atwood, née le 18 n...",78,469,3,0,"margaret eleanor « peggy » atwood, née le 18 n...","margaret eleanor « peggy » atwood, née le 18 n..."
23,"Marion Brunet, née en 1976 dans le Vaucluse, e...",25,150,1,0,"marion brunet, née en 1976 dans le vaucluse, e...","marion brunet, née en 1976 dans le vaucluse, e..."
24,"Cécile Coulon, née le 13 juin 1990 à Clermont-...",17,123,2,0,"cécile coulon, née le 13 juin 1990 à clermont-...","cécile coulon, née le 13 juin 1990 à clermont-..."
25,"Paolo Rumiz, né le 20 décembre 1947 à Trieste,...",17,98,2,0,"paolo rumiz, né le 20 décembre 1947 à trieste,...","paolo rumiz, né le 20 décembre 1947 à trieste,..."
26,"Éléonore Pourriat est une actrice, scénariste ...",9,72,0,0,"éléonore pourriat est une actrice, scénariste ...","éléonore pourriat est une actrice, scénariste ..."
27,"Jean-Paul Dubois, né le 20 février 1950 à Toul...",13,77,2,0,"jean-paul dubois, né le 20 février 1950 à toul...","jean-paul dubois, né le 20 février 1950 à toul..."
28,"Jean-Baptiste Andrea, né le 4 avril 1971 à Sai...",17,119,2,0,"jean-baptiste andrea, né le 4 avril 1971 à sai...","jean-baptiste andrea, né le 4 avril 1971 à sai..."
29,Christophe Tison est un journaliste et écrivai...,13,77,0,0,christophe tison est un journaliste et écrivai...,christophe tison est un journaliste et écrivai...
...,...,...,...,...,...,...,...
109,Jean Anouilh (/a.nuj/) est un écrivain et dram...,308,1863,5,0,jean anouilh (/a.nuj/) est un écrivain et dram...,jean anouilh (/a.nuj/) est un écrivain et dram...
110,"Pierre Ambroise Choderlos de Laclos, né à Amie...",53,311,3,0,"pierre ambroise choderlos de laclos, né à amie...","pierre ambroise choderlos de laclos, né à amie..."
111,"Victor Hugo est un poète, dramaturge, écrivain...",406,2497,6,2,"victor hugo est un poète, dramaturge, écrivain...","victor hugo est un poète, dramaturge, écrivain..."
112,Anna Gavalda est une femme de lettres français...,15,95,2,0,anna gavalda est une femme de lettres français...,anna gavalda est une femme de lettres français...
113,"Marie-Madeleine Pioche de La Vergne, comtesse ...",34,183,4,0,"marie-madeleine pioche de la vergne, comtesse ...","marie-madeleine pioche de la vergne, comtesse ..."
114,Émile Zola est un écrivain et journaliste fran...,174,1071,3,0,émile zola est un écrivain et journaliste fran...,émile zola est un écrivain et journaliste fran...
115,"Jean-Baptiste Poquelin, dit Molière, est un co...",431,2711,5,1,"jean-baptiste poquelin, dit molière, est un co...","jean-baptiste poquelin, dit molière, est un co..."
116,Alexandre Dumas (dit aussi Alexandre Dumas pèr...,264,1674,4,1,alexandre dumas (dit aussi alexandre dumas pèr...,alexandre dumas (dit aussi alexandre dumas pèr...
117,Gilles Legardinier est un écrivain et scénaris...,25,142,2,0,gilles legardinier est un écrivain et scénaris...,gilles legardinier est un écrivain et scénaris...
118,"Edmond Rostand, né le 1er avril 1868 à Marseil...",61,373,3,0,"edmond rostand, né le 1er avril 1868 à marseil...","edmond rostand, né le 1er avril 1868 à marseil..."
119,Ernest Miller Hemingway [ˈɝnɪst ˈmɪlɚ ˈhɛmɪŋˌw...,478,2838,8,1,ernest miller hemingway [ˈɝnɪst ˈmɪlɚ ˈhɛmɪŋˌw...,ernest miller hemingway [ˈɝnɪst ˈmɪlɚ ˈhɛmɪŋˌw...
120,"Guillaume Musso, né le 6 juin 1974 à Antibes, ...",13,72,2,0,"guillaume musso, né le 6 juin 1974 à antibes, ...","guillaume musso, né le 6 juin 1974 à antibes, ..."
121,"Edgar Allan Poe [ˈɛdɡɚ ˈælən poʊ], né le 19 ja...",535,3273,7,0,"edgar allan poe [ˈɛdɡɚ ˈælən poʊ], né le 19 ja...","edgar allan poe [ˈɛdɡɚ ˈælən poʊ], né le 19 ja..."
122,"Jonas Jonasson, né le 6 juillet 1961 à Växjö, ...",38,214,2,0,"jonas jonasson, né le 6 juillet 1961 à växjö, ...","jonas jonasson, né le 6 juillet 1961 à växjö, ..."
123,"Guillaume Musso, né le 6 juin 1974 à Antibes, ...",13,72,2,0,"guillaume musso, né le 6 juin 1974 à antibes, ...","guillaume musso, né le 6 juin 1974 à antibes, ..."
124,"Jean Edith Camilla Läckberg Eriksson, née le 3...",92,550,2,0,"jean edith camilla läckberg eriksson, née le 3...","jean edith camilla läckberg eriksson, née le 3..."
125,Arthur Conan Doyle (né Arthur Ignatius Conan D...,126,740,5,1,arthur conan doyle (né arthur ignatius conan d...,arthur conan doyle (né arthur ignatius conan d...
126,"William Shakespeare, baptisé le 26 avril 1564 ...",246,1615,8,0,"william shakespeare, baptisé le 26 avril 1564 ...","william shakespeare, baptisé le 26 avril 1564 ..."
127,"Jean-Baptiste Poquelin, dit Molière, est un co...",431,2711,5,1,"jean-baptiste poquelin, dit molière, est un co...","jean-baptiste poquelin, dit molière, est un co..."
128,"Pierre Corneille, aussi appelé « le Grand Corn...",801,4790,10,5,"pierre corneille, aussi appelé « le grand corn...","pierre corneille, aussi appelé « le grand corn..."
129,"Veronica Anne Roth, née le 19 août 1988 à New ...",102,635,7,0,"veronica anne roth, née le 19 août 1988 à new ...","veronica anne roth, née le 19 août 1988 à new ..."
130,Anna Gavalda est une femme de lettres français...,15,95,2,0,anna gavalda est une femme de lettres français...,anna gavalda est une femme de lettres français...
131,Marguerite Duras — nom de plume de Marguerite ...,339,2098,7,1,marguerite duras — nom de plume de marguerite ...,marguerite duras — nom de plume de marguerite ...
132,Paula Hawkins (née le 26 août 1972) est une éc...,19,108,1,0,paula hawkins (née le 26 août 1972) est une éc...,paula hawkins (née le 26 août 1972) est une éc...
133,"J. D. Salinger, nom de plume de Jerome David S...",159,956,5,2,"j. d. salinger, nom de plume de jerome david s...","j. d. salinger, nom de plume de jerome david s..."
134,"Gaston Leroux est un romancier français, né l...",37,202,4,0,"gaston leroux est un romancier français, né l...","gaston leroux est un romancier français, né l..."
135,"Philip Pullman, né le 19 octobre 1946 à Norwic...",27,152,2,1,"philip pullman, né le 19 octobre 1946 à norwic...","philip pullman, né le 19 octobre 1946 à norwic..."
136,"Ken Follett, né le 5 juin 1949 à Cardiff, est ...",20,121,2,0,"ken follett, né le 5 juin 1949 à cardiff, est ...","ken follett, né le 5 juin 1949 à cardiff, est ..."
137,Émile Zola est un écrivain et journaliste fran...,174,1071,3,0,émile zola est un écrivain et journaliste fran...,émile zola est un écrivain et journaliste fran...
138,"Honoré de Balzac, né Honoré Balzac à Tours le ...",617,3880,8,2,"honoré de balzac, né honoré balzac à tours le ...","honoré de balzac, né honoré balzac à tours le ..."

### Removing Punctuation & Special Characters

**Tips :** 
- Use withoutLineReturn column
- Use `regex` to keep words : `[^\w\s]` If you need to test regex, use http://regex101.com

In [81]:
df["withoutLineReturn"].str.replace('[^\w\s]','') # replace any character that is not a word by nothing

0      paolo rumiz né le 20 décembre 1947 à trieste e...
1      saverio tomasella est un psychanalyste et écri...
2      annelise heurtier née en 1979 à villefranchesu...
3      erik orsenna pseudonyme déric arnoult est un é...
4      christophe tison est un journaliste et écrivai...
                             ...
134    gaston leroux est un romancier français né  le...
135    philip pullman né le 19 octobre 1946 à norwich...
136    ken follett né le 5 juin 1949 à cardiff est un...
137    émile zola est un écrivain et journaliste fran...
138    honoré de balzac né honoré balzac à tours le 2...
Name: withoutLineReturn, Length: 139, dtype: object

In [29]:
df['withoutPunctuation'] = df["withoutLineReturn"].str.replace('[^\w\s]','')
df.head()

,description,wordCount,characterCount,numericCount,isUpperCase,lowercase,withoutLineReturn,withoutPunctuation
0,"Paolo Rumiz, né le 20 décembre 1947 à Trieste,...",17,98,2,0,"paolo rumiz, né le 20 décembre 1947 à trieste,...","paolo rumiz, né le 20 décembre 1947 à trieste,...",paolo rumiz né le 20 décembre 1947 à trieste e...
1,Saverio Tomasella est un psychanalyste et écri...,15,96,1,0,saverio tomasella est un psychanalyste et écri...,saverio tomasella est un psychanalyste et écri...,saverio tomasella est un psychanalyste et écri...
2,"Annelise Heurtier, née en 1979 à Villefranche-...",16,122,1,0,"annelise heurtier, née en 1979 à villefranche-...","annelise heurtier, née en 1979 à villefranche-...",annelise heurtier née en 1979 à villefranchesu...
3,"Erik Orsenna, pseudonyme d’Éric Arnoult, est u...",20,125,2,0,"erik orsenna, pseudonyme d’éric arnoult, est u...","erik orsenna, pseudonyme d’éric arnoult, est u...",erik orsenna pseudonyme déric arnoult est un é...
4,Christophe Tison est un journaliste et écrivai...,13,77,0,0,christophe tison est un journaliste et écrivai...,christophe tison est un journaliste et écrivai...,christophe tison est un journaliste et écrivai...

### Remove stopwords

In [30]:
import nltk
from nltk.corpus import stopwords
#nltk.download('stopwords')
stop = stopwords.words('french')

In [31]:
stop

['au',
 'aux',
 'avec',
 'ce',
 'ces',
 'dans',
 'de',
 'des',
 'du',
 'elle',
 'en',
 'et',
 'eux',
 'il',
 'ils',
 'je',
 'la',
 'le',
 'les',
 'leur',
 'lui',
 'ma',
 'mais',
 'me',
 'même',
 'mes',
 'moi',
 'mon',
 'ne',
 'nos',
 'notre',
 'nous',
 'on',
 'ou',
 'par',
 'pas',
 'pour',
 'qu',
 'que',
 'qui',
 'sa',
 'se',
 'ses',
 'son',
 'sur',
 'ta',
 'te',
 'tes',
 'toi',
 'ton',
 'tu',
 'un',
 'une',
 'vos',
 'votre',
 'vous',
 'c',
 'd',
 'j',
 'l',
 'à',
 'm',
 'n',
 's',
 't',
 'y',
 'été',
 'étée',
 'étées',
 'étés',
 'étant',
 'étante',
 'étants',
 'étantes',
 'suis',
 'es',
 'est',
 'sommes',
 'êtes',
 'sont',
 'serai',
 'seras',
 'sera',
 'serons',
 'serez',
 'seront',
 'serais',
 'serait',
 'serions',
 'seriez',
 'seraient',
 'étais',
 'était',
 'étions',
 'étiez',
 'étaient',
 'fus',
 'fut',
 'fûmes',
 'fûtes',
 'furent',
 'sois',
 'soit',
 'soyons',
 'soyez',
 'soient',
 'fusse',
 'fusses',
 'fût',
 'fussions',
 'fussiez',
 'fussent',
 'ayant',
 'ayante',
 'ayantes',
 'ayants',
 'eu',
 'eue',
 'eues',
 'eus',
 'ai',
 'as',
 'avons',
 'avez',
 'ont',
 'aurai',
 'auras',
 'aura',
 'aurons',
 'aurez',
 'auront',
 'aurais',
 'aurait',
 'aurions',
 'auriez',
 'auraient',
 'avais',
 'avait',
 'avions',
 'aviez',
 'avaient',
 'eut',
 'eûmes',
 'eûtes',
 'eurent',
 'aie',
 'aies',
 'ait',
 'ayons',
 'ayez',
 'aient',
 'eusse',
 'eusses',
 'eût',
 'eussions',
 'eussiez',
 'eussent']

**Tips :** Use `withoutPunctuaction` column

In [42]:
df['withoutStopwords'] = df['withoutPunctuation'].apply(lambda x: ' '.join([item for item in x.split(' ') if item not in stop]))
df.head()

,description,wordCount,characterCount,numericCount,isUpperCase,lowercase,withoutLineReturn,withoutPunctuation,withoutStopwords
0,"Paolo Rumiz, né le 20 décembre 1947 à Trieste,...",17,98,2,0,"paolo rumiz, né le 20 décembre 1947 à trieste,...","paolo rumiz, né le 20 décembre 1947 à trieste,...",paolo rumiz né le 20 décembre 1947 à trieste e...,paolo rumiz né 20 décembre 1947 trieste journa...
1,Saverio Tomasella est un psychanalyste et écri...,15,96,1,0,saverio tomasella est un psychanalyste et écri...,saverio tomasella est un psychanalyste et écri...,saverio tomasella est un psychanalyste et écri...,saverio tomasella psychanalyste écrivain franç...
2,"Annelise Heurtier, née en 1979 à Villefranche-...",16,122,1,0,"annelise heurtier, née en 1979 à villefranche-...","annelise heurtier, née en 1979 à villefranche-...",annelise heurtier née en 1979 à villefranchesu...,annelise heurtier née 1979 villefranchesursaôn...
3,"Erik Orsenna, pseudonyme d’Éric Arnoult, est u...",20,125,2,0,"erik orsenna, pseudonyme d’éric arnoult, est u...","erik orsenna, pseudonyme d’éric arnoult, est u...",erik orsenna pseudonyme déric arnoult est un é...,erik orsenna pseudonyme déric arnoult écrivain...
4,Christophe Tison est un journaliste et écrivai...,13,77,0,0,christophe tison est un journaliste et écrivai...,christophe tison est un journaliste et écrivai...,christophe tison est un journaliste et écrivai...,christophe tison journaliste écrivain français...

### Tokenization

In [43]:
from nltk import tokenize
tokenizer = tokenize.SpaceTokenizer()

**Tips :** Use `withoutStopwords` column

,description,wordCount,characterCount,numericCount,isUppercase,lowercase,withoutLineReturn,withoutPunctuaction,withoutStopwords,tokenized
0,"Paolo Rumiz, né le 20 décembre 1947 à Trieste,...",17,98,2,0,"paolo rumiz, né le 20 décembre 1947 à trieste,...","paolo rumiz, né le 20 décembre 1947 à trieste,...",paolo rumiz né le 20 décembre 1947 à trieste e...,paolo rumiz né 20 décembre 1947 trieste journa...,"[paolo, rumiz, né, 20, décembre, 1947, trieste..."
1,Saverio Tomasella est un psychanalyste et écri...,15,96,1,0,saverio tomasella est un psychanalyste et écri...,saverio tomasella est un psychanalyste et écri...,saverio tomasella est un psychanalyste et écri...,saverio tomasella psychanalyste écrivain franç...,"[saverio, tomasella, psychanalyste, écrivain, ..."
2,"Annelise Heurtier, née en 1979 à Villefranche-...",16,122,1,0,"annelise heurtier, née en 1979 à villefranche-...","annelise heurtier, née en 1979 à villefranche-...",annelise heurtier née en 1979 à villefranchesu...,annelise heurtier née 1979 villefranchesursaôn...,"[annelise, heurtier, née, 1979, villefranchesu..."
3,"Erik Orsenna, pseudonyme d’Éric Arnoult, est u...",21,125,2,0,"erik orsenna, pseudonyme d’éric arnoult, est u...","erik orsenna, pseudonyme d’éric arnoult, est u...",erik orsenna pseudonyme déric arnoult est un é...,erik orsenna pseudonyme déric arnoult écrivain...,"[erik, orsenna, pseudonyme, déric, arnoult, éc..."
4,Christophe Tison est un journaliste et écrivai...,13,77,0,0,christophe tison est un journaliste et écrivai...,christophe tison est un journaliste et écrivai...,christophe tison est un journaliste et écrivai...,christophe tison journaliste écrivain français...,"[christophe, tison, journaliste, écrivain, fra..."
5,"Sylvain Prudhomme, né en 1979 à La Seyne-sur-M...",33,201,1,0,"sylvain prudhomme, né en 1979 à la seyne-sur-m...","sylvain prudhomme, né en 1979 à la seyne-sur-m...",sylvain prudhomme né en 1979 à la seynesurmer ...,sylvain prudhomme né 1979 seynesurmer écrivain...,"[sylvain, prudhomme, né, 1979, seynesurmer, éc..."
6,Sally Nicholls (née le 22 juin 1983 à Stockton...,19,121,2,0,sally nicholls (née le 22 juin 1983 à stockton...,sally nicholls (née le 22 juin 1983 à stockton...,sally nicholls née le 22 juin 1983 à stocktono...,sally nicholls née 22 juin 1983 stocktonontees...,"[sally, nicholls, née, 22, juin, 1983, stockto..."
7,"Maxime Drouot, connu sous les pseudonymes de M...",37,235,2,0,"maxime drouot, connu sous les pseudonymes de m...","maxime drouot, connu sous les pseudonymes de m...",maxime drouot connu sous les pseudonymes de ma...,maxime drouot connu sous les pseudonymes maxim...,"[maxime, drouot, connu, sous, les, pseudonymes..."
8,"Ivan Jablonka, né le 23 octobre 1973 à Paris, ...",21,147,2,0,"ivan jablonka, né le 23 octobre 1973 à paris, ...","ivan jablonka, né le 23 octobre 1973 à paris, ...",ivan jablonka né le 23 octobre 1973 à paris es...,ivan jablonka né 23 octobre 1973 paris histori...,"[ivan, jablonka, né, 23, octobre, 1973, paris,..."
9,"Jean-Pierre Cabanes, né le 31 juillet 1949 à M...",15,93,2,0,"jean-pierre cabanes, né le 31 juillet 1949 à m...","jean-pierre cabanes, né le 31 juillet 1949 à m...",jeanpierre cabanes né le 31 juillet 1949 à mon...,jeanpierre cabanes né 31 juillet 1949 montpell...,"[jeanpierre, cabanes, né, 31, juillet, 1949, m..."
10,Alain Ayroles est un scénariste de bande dessi...,16,91,2,0,alain ayroles est un scénariste de bande dessi...,alain ayroles est un scénariste de bande dessi...,alain ayroles est un scénariste de bande dessi...,alain ayroles scénariste bande dessinée né 26 ...,"[alain, ayroles, scénariste, bande, dessinée, ..."
11,"Martha Wells, née le 1er septembre 1964 à Fort...",21,125,1,0,"martha wells, née le 1er septembre 1964 à fort...","martha wells, née le 1er septembre 1964 à fort...",martha wells née le 1er septembre 1964 à fort ...,martha wells née 1er septembre 1964 fort worth...,"[martha, wells, née, 1er, septembre, 1964, for..."
12,"Amélie Nothomb /ameli nɔtɔ̃b/, nom de plume de...",129,832,3,0,"amélie nothomb /ameli nɔtɔ̃b/, nom de plume de...","amélie nothomb /ameli nɔtɔ̃b/, nom de plume de...",amélie nothomb ameli nɔtɔb nom de plume de fab...,amélie nothomb ameli nɔtɔb nom plume fabienne ...,"[amélie, nothomb, ameli, nɔtɔb, nom, plume, fa..."
13,Florence Hinckel est une autrice française de...,12,82,0,0,florence hinckel est une autrice française de...,florence hinckel est une autrice française de...,florence hinckel est une autrice française de...,florence hinckel autrice française romans enfa...,"[florence, hinckel, autrice, française, romans..."
14,"Karine Tuil, née le 3 mai 1972 à Paris, est un...",13,69,2,0,"karine tuil, née le 3 mai 1972 à paris, est un...","karine tuil, née le 3 mai 1972 à paris, est un...",karine tuil née le 3 mai 1972 à paris est une ...,karine tuil née 3 mai 1972 paris romancière fr...,"[karine, tuil, née, 3, mai, 1972, paris, roman..."
15,"Jérémie Kisling, né Jérémie Tschanz à Lausanne...",33,238,1,0,"jérémie kisling, né jérémie tschanz à lausanne...","jérémie kisling, né jérémie tschanz à lausanne...",jérémie kisling né jérémie tschanz à lausanne ...,jérémie kisling né jérémie tschanz lausanne 27...,"[jérémie, kisling, né, jérémie, tschanz, lausa..."
16,"Née le 3 janvier 1969 à Bayonne, au Pays basqu...",122,730,4,1,"née le 3 janvier 1969 à bayonne, au pays basqu...","née le 3 janvier 1969 à bayonne, au pays basqu...",née le 3 janvier 1969 à bayonne au pays basque...,née 3 janvier 1969 bayonne pays basque marie d...,"[née, 3, janvier, 1969, bayonne, pays, basque,..."
17,"Léonora Miano, née le 12 mars 1973 à Douala (C...",18,124,2,0,"léonora miano, née le 12 mars 1973 à douala (c...","léonora miano, née le 12 mars 1973 à douala (c...",léonora miano née le 12 mars 1973 à douala cam...,léonora miano née 12 mars 1973 douala cameroun...,"[léonora, miano, née, 12, mars, 1973, douala, ..."
18,"Ottessa Moshfegh, née en 20 mai 1981 à Boston ...",16,98,2,0,"ottessa moshfegh, née en 20 mai 1981 à boston ...","ottessa moshfegh, née en 20 mai 1981 à boston ...",ottessa moshfegh née en 20 mai 1981 à boston d...,ottessa moshfegh née 20 mai 1981 boston massac...,"[ottessa, moshfegh, née, 20, mai, 1981, boston..."
19,"David Lagercrantz, né le 4 septembre 1962 à So...",60,352,2,0,"david lagercrantz, né le 4 septembre 1962 à so...","david lagercrantz, né le 4 septembre 1962 à so...",david lagercrantz né le 4 septembre 1962 à sol...,david lagercrantz né 4 septembre 1962 solna jo...,"[david, lagercrantz, né, 4, septembre, 1962, s..."
20,"Jonathan Coe, né le 19 août 1961 à Birmingham,...",13,75,2,0,"jonathan coe, né le 19 août 1961 à birmingham,...","jonathan coe, né le 19 août 1961 à birmingham,...",jonathan coe né le 19 août 1961 à birmingham e...,jonathan coe né 19 août 1961 birmingham écriva...,"[jonathan, coe, né, 19, août, 1961, birmingham..."
21,"Dominique Forma, né en 1962 à Puteaux, est un ...",14,99,1,0,"dominique forma, né en 1962 à puteaux, est un ...","dominique forma, né en 1962 à puteaux, est un ...",dominique forma né en 1962 à puteaux est un sc...,dominique forma né 1962 puteaux scénariste réa...,"[dominique, forma, né, 1962, puteaux, scénaris..."
22,"Margaret Eleanor « Peggy » Atwood, née le 18 n...",78,469,3,0,"margaret eleanor « peggy » atwood, née le 18 n...","margaret eleanor « peggy » atwood, née le 18 n...",margaret eleanor peggy atwood née le 18 nove...,margaret eleanor peggy atwood née 18 novembre ...,"[margaret, eleanor, peggy, atwood, née, 18, no..."
23,"Marion Brunet, née en 1976 dans le Vaucluse, e...",25,150,1,0,"marion brunet, née en 1976 dans le vaucluse, e...","marion brunet, née en 1976 dans le vaucluse, e...",marion brunet née en 1976 dans le vaucluse est...,marion brunet née 1976 vaucluse femme lettres ...,"[marion, brunet, née, 1976, vaucluse, femme, l..."
24,"Cécile Coulon, née le 13 juin 1990 à Clermont-...",17,123,2,0,"cécile coulon, née le 13 juin 1990 à clermont-...","cécile coulon, née le 13 juin 1990 à clermont-...",cécile coulon née le 13 juin 1990 à clermontfe...,cécile coulon née 13 juin 1990 clermontferrand...,"[cécile, coulon, née, 13, juin, 1990, clermont..."
25,"Paolo Rumiz, né le 20 décembre 1947 à Trieste,...",17,98,2,0,"paolo rumiz, né le 20 décembre 1947 à trieste,...","paolo rumiz, né le 20 décembre 1947 à trieste,...",paolo rumiz né le 20 décembre 1947 à trieste e...,paolo rumiz né 20 décembre 1947 trieste journa...,"[paolo, rumiz, né, 20, décembre, 1947, trieste..."
26,"Éléonore Pourriat est une actrice, scénariste ...",9,72,0,0,"éléonore pourriat est une actrice, scénariste ...","éléonore pourriat est une actrice, scénariste ...",éléonore pourriat est une actrice scénariste e...,éléonore pourriat actrice scénariste réalisatr...,"[éléonore, pourriat, actrice, scénariste, réal..."
27,"Jean-Paul Dubois, né le 20 février 1950 à Toul...",13,77,2,0,"jean-paul dubois, né le 20 février 1950 à toul...","jean-paul dubois, né le 20 février 1950 à toul...",jeanpaul dubois né le 20 février 1950 à toulou...,jeanpaul dubois né 20 février 1950 toulouse éc...,"[jeanpaul, dubois, né, 20, février, 1950, toul..."
28,"Jean-Baptiste Andrea, né le 4 avril 1971 à Sai...",17,119,2,0,"jean-baptiste andrea, né le 4 avril 1971 à sai...","jean-baptiste andrea, né le 4 avril 1971 à sai...",jeanbaptiste andrea né le 4 avril 1971 à saint...,jeanbaptiste andrea né 4 avril 1971 saintgerma...,"[jeanbaptiste, andrea, né, 4, avril, 1971, sai..."
29,Christophe Tison est un journaliste et écrivai...,13,77,0,0,christophe tison est un journaliste et écrivai...,christophe tison est un journaliste et écrivai...,christophe tison est un journaliste et écrivai...,christophe tison journaliste écrivain français...,"[christophe, tison, journaliste, écrivain, fra..."
...,...,...,...,...,...,...,...,...,...,...
109,Jean Anouilh (/a.nuj/) est un écrivain et dram...,307,1863,5,0,jean anouilh (/a.nuj/) est un écrivain et dram...,jean anouilh (/a.nuj/) est un écrivain et dram...,jean anouilh anuj est un écrivain et dramaturg...,jean anouilh anuj écrivain dramaturge français...,"[jean, anouilh, anuj, écrivain, dramaturge, fr..."
110,"Pierre Ambroise Choderlos de Laclos, né à Amie...",53,311,3,0,"pierre ambroise choderlos de laclos, né à amie...","pierre ambroise choderlos de laclos, né à amie...",pierre ambroise choderlos de laclos né à amien...,pierre ambroise choderlos laclos né amiens 18 ...,"[pierre, ambroise, choderlos, laclos, né, amie..."
111,"Victor Hugo est un poète, dramaturge, écrivain...",409,2497,6,2,"victor hugo est un poète, dramaturge, écrivain...","victor hugo est un poète, dramaturge, écrivain...",victor hugo est un poète dramaturge écrivain r...,victor hugo poète dramaturge écrivain romancie...,"[victor, hugo, poète, dramaturge, écrivain, ro..."
112,Anna Gavalda est une femme de lettres français...,15,95,2,0,anna gavalda est une femme de lettres français...,anna gavalda est une femme de lettres français...,anna gavalda est une femme de lettres français...,anna gavalda femme lettres française née 9 déc...,"[anna, gavalda, femme, lettres, française, née..."
113,"Marie-Madeleine Pioche de La Vergne, comtesse ...",34,183,4,0,"marie-madeleine pioche de la vergne, comtesse ...","marie-madeleine pioche de la vergne, comtesse ...",mariemadeleine pioche de la vergne comtesse de...,mariemadeleine pioche vergne comtesse fayette ...,"[mariemadeleine, pioche, vergne, comtesse, fay..."
114,Émile Zola est un écrivain et journaliste fran...,176,1071,3,0,émile zola est un écrivain et journaliste fran...,émile zola est un écrivain et journaliste fran...,émile zola est un écrivain et journaliste fran...,émile zola écrivain journaliste français né 2 ...,"[émile, zola, écrivain, journaliste, français,..."
115,"Jean-Baptiste Poquelin, dit Molière, est un co...",434,2711,5,1,"jean-baptiste poquelin, dit molière, est un co...","jean-baptiste poquelin, dit molière, est un co...",jeanbaptiste poquelin dit molière est un coméd...,jeanbaptiste poquelin dit molière comédien dra...,"[jeanbaptiste, poquelin, dit, molière, comédie..."
116,Alexandre Dumas (dit aussi Alexandre Dumas pèr...,267,1674,4,1,alexandre dumas (dit aussi alexandre dumas pèr...,alexandre dumas (dit aussi alexandre dumas pèr...,alexandre dumas dit aussi alexandre dumas père...,alexandre dumas dit aussi alexandre dumas père...,"[alexandre, dumas, dit, aussi, alexandre, duma..."
117,Gilles Legardinier est un écrivain et scénaris...,24,142,2,0,gilles legardinier est un écrivain et scénaris...,gilles legardinier est un écrivain et scénaris...,gilles legardinier est un écrivain et scénaris...,gilles legardinier écrivain scénariste françai...,"[gilles, legardinier, écrivain, scénariste, fr..."
118,"Edmond Rostand, né le 1er avril 1868 à Marseil...",62,373,3,0,"edmond rostand, né le 1er avril 1868 à marseil...","edmond rostand, né le 1er avril 1868 à marseil...",edmond rostand né le 1er avril 1868 à marseill...,edmond rostand né 1er avril 1868 marseille mor...,"[edmond, rostand, né, 1er, avril, 1868, marsei..."
119,Ernest Miller Hemingway [ˈɝnɪst ˈmɪlɚ ˈhɛmɪŋˌw...,483,2838,8,1,ernest miller hemingway [ˈɝnɪst ˈmɪlɚ ˈhɛmɪŋˌw...,ernest miller hemingway [ˈɝnɪst ˈmɪlɚ ˈhɛmɪŋˌw...,ernest miller hemingway ˈɝnɪst ˈmɪlɚ ˈhɛmɪŋˌwe...,ernest miller hemingway ˈɝnɪst ˈmɪlɚ ˈhɛmɪŋˌwe...,"[ernest, miller, hemingway, ˈɝnɪst, ˈmɪlɚ, ˈhɛ..."
120,"Guillaume Musso, né le 6 juin 1974 à Antibes, ...",13,72,2,0,"guillaume musso, né le 6 juin 1974 à antibes, ...","guillaume musso, né le 6 juin 1974 à antibes, ...",guillaume musso né le 6 juin 1974 à antibes es...,guillaume musso né 6 juin 1974 antibes romanci...,"[guillaume, musso, né, 6, juin, 1974, antibes,..."
121,"Edgar Allan Poe [ˈɛdɡɚ ˈælən poʊ], né le 19 ja...",539,3273,7,0,"edgar allan poe [ˈɛdɡɚ ˈælən poʊ], né le 19 ja...","edgar allan poe [ˈɛdɡɚ ˈælən poʊ], né le 19 ja...",edgar allan poe ˈɛdɡɚ ˈælən poʊ né le 19 janvi...,edgar allan poe ˈɛdɡɚ ˈælən poʊ né 19 janvier ...,"[edgar, allan, poe, ˈɛdɡɚ, ˈælən, poʊ, né, 19,..."
122,"Jonas Jonasson, né le 6 juillet 1961 à Växjö, ...",39,214,2,0,"jonas jonasson, né le 6 juillet 1961 à växjö, ...","jonas jonasson, né le 6 juillet 1961 à växjö, ...",jonas jonasson né le 6 juillet 1961 à växjö es...,jonas jonasson né 6 juillet 1961 växjö écrivai...,"[jonas, jonasson, né, 6, juillet, 1961, växjö,..."
123,"Guillaume Musso, né le 6 juin 1974 à Antibes, ...",13,72,2,0,"guillaume musso, né le 6 juin 1974 à antibes, ...","guillaume musso, né le 6 juin 1974 à antibes, ...",guillaume musso né le 6 juin 1974 à antibes es...,guillaume musso né 6 juin 1974 antibes romanci...,"[guillaume, musso, né, 6, juin, 1974, antibes,..."
124,"Jean Edith Camilla Läckberg Eriksson, née le 3...",92,550,2,0,"jean edith camilla läckberg eriksson, née le 3...","jean edith camilla läckberg eriksson, née le 3...",jean edith camilla läckberg eriksson née le 30...,jean edith camilla läckberg eriksson née 30 ao...,"[jean, edith, camilla, läckberg, eriksson, née..."
125,Arthur Conan Doyle (né Arthur Ignatius Conan D...,127,740,5,1,arthur conan doyle (né arthur ignatius conan d...,arthur conan doyle (né arthur ignatius conan d...,arthur conan doyle né arthur ignatius conan do...,arthur conan doyle né arthur ignatius conan do...,"[arthur, conan, doyle, né, arthur, ignatius, c..."
126,"William Shakespeare, baptisé le 26 avril 1564 ...",249,1615,8,0,"william shakespeare, baptisé le 26 avril 1564 ...","william shakespeare, baptisé le 26 avril 1564 ...",william shakespeare baptisé le 26 avril 1564 à...,william shakespeare baptisé 26 avril 1564 stra...,"[william, shakespeare, baptisé, 26, avril, 156..."
127,"Jean-Baptiste Poquelin, dit Molière, est un co...",434,2711,5,1,"jean-baptiste poquelin, dit molière, est un co...","jean-baptiste poquelin, dit molière, est un co...",jeanbaptiste poquelin dit molière est un coméd...,jeanbaptiste poquelin dit molière comédien dra...,"[jeanbaptiste, poquelin, dit, molière, comédie..."
128,"Pierre Corneille, aussi appelé « le Grand Corn...",805,4790,10,5,"pierre corneille, aussi appelé « le grand corn...","pierre corneille, aussi appelé « le grand corn...",pierre corneille aussi appelé le grand cornei...,pierre corneille aussi appelé grand corneille ...,"[pierre, corneille, aussi, appelé, grand, corn..."
129,"Veronica Anne Roth, née le 19 août 1988 à New ...",102,635,7,0,"veronica anne roth, née le 19 août 1988 à new ...","veronica anne roth, née le 19 août 1988 à new ...",veronica anne roth née le 19 août 1988 à new y...,veronica anne roth née 19 août 1988 new york p...,"[veronica, anne, roth, née, 19, août, 1988, ne..."
130,Anna Gavalda est une femme de lettres français...,15,95,2,0,anna gavalda est une femme de lettres français...,anna gavalda est une femme de lettres français...,anna gavalda est une femme de lettres français...,anna gavalda femme lettres française née 9 déc...,"[anna, gavalda, femme, lettres, française, née..."
131,Marguerite Duras — nom de plume de Marguerite ...,343,2098,7,1,marguerite duras — nom de plume de marguerite ...,marguerite duras — nom de plume de marguerite ...,marguerite duras nom de plume de marguerite d...,marguerite duras nom plume marguerite donnadie...,"[marguerite, duras, nom, plume, marguerite, do..."
132,Paula Hawkins (née le 26 août 1972) est une éc...,19,108,1,0,paula hawkins (née le 26 août 1972) est une éc...,paula hawkins (née le 26 août 1972) est une éc...,paula hawkins née le 26 août 1972 est une écri...,paula hawkins née 26 août 1972 écrivaine brita...,"[paula, hawkins, née, 26, août, 1972, écrivain..."
133,"J. D. Salinger, nom de plume de Jerome David S...",161,956,5,2,"j. d. salinger, nom de plume de jerome david s...","j. d. salinger, nom de plume de jerome david s...",j d salinger nom de plume de jerome david sali...,salinger nom plume jerome david salinger dʒeˈr...,"[salinger, nom, plume, jerome, david, salinger..."
134,"Gaston Leroux est un romancier français, né l...",35,202,4,0,"gaston leroux est un romancier français, né l...","gaston leroux est un romancier français, né l...",gaston leroux est un romancier français né le...,gaston leroux romancier français né 6 mai 1868...,"[gaston, leroux, romancier, français, né, 6, m..."
135,"Philip Pullman, né le 19 octobre 1946 à Norwic...",27,152,2,1,"philip pullman, né le 19 octobre 1946 à norwic...","philip pullman, né le 19 octobre 1946 à norwic...",philip pullman né le 19 octobre 1946 à norwich...,philip pullman né 19 octobre 1946 norwich norf...,"[philip, pullman, né, 19, octobre, 1946, norwi..."
136,"Ken Follett, né le 5 juin 1949 à Cardiff, est ...",20,121,2,0,"ken follett, né le 5 juin 1949 à cardiff, est ...","ken follett, né le 5 juin 1949 à cardiff, est ...",ken follett né le 5 juin 1949 à cardiff est un...,ken follett né 5 juin 1949 cardiff écrivain ga...,"[ken, follett, né, 5, juin, 1949, cardiff, écr..."
137,Émile Zola est un écrivain et journaliste fran...,176,1071,3,0,émile zola est un écrivain et journaliste fran...,émile zola est un écrivain et journaliste fran...,émile zola est un écrivain et journaliste fran...,émile zola écrivain journaliste français né 2 ...,"[émile, zola, écrivain, journaliste, français,..."
138,"Honoré de Balzac, né Honoré Balzac à Tours le ...",624,3880,8,2,"honoré de balzac, né honoré balzac à tours le ...","honoré de balzac, né honoré balzac à tours le ...",honoré de balzac né honoré balzac à tours le 2...,honoré balzac né honoré balzac tours 20 mai 17...,"[honoré, balzac, né, honoré, balzac, tours, 20..."

### Stemming

In [16]:
from nltk.stem.snowball import SnowballStemmer
stemmer = SnowballStemmer("french", ignore_stopwords=True)

**Tips :** 
- Use `withoutStopwords` column
- If you want to transform a list of string into a string, you can use `' '.join([])`

,description,wordCount,characterCount,numericCount,isUppercase,lowercase,withoutLineReturn,withoutPunctuaction,withoutStopwords,tokenized,stemming
0,"Paolo Rumiz, né le 20 décembre 1947 à Trieste,...",17,98,2,0,"paolo rumiz, né le 20 décembre 1947 à trieste,...","paolo rumiz, né le 20 décembre 1947 à trieste,...",paolo rumiz né le 20 décembre 1947 à trieste e...,paolo rumiz né 20 décembre 1947 trieste journa...,"[paolo, rumiz, né, 20, décembre, 1947, trieste...",paolo rumiz né 20 décembr 1947 triest journal ...
1,Saverio Tomasella est un psychanalyste et écri...,15,96,1,0,saverio tomasella est un psychanalyste et écri...,saverio tomasella est un psychanalyste et écri...,saverio tomasella est un psychanalyste et écri...,saverio tomasella psychanalyste écrivain franç...,"[saverio, tomasella, psychanalyste, écrivain, ...",saverio tomasel psychanalyst écrivain franc né...
2,"Annelise Heurtier, née en 1979 à Villefranche-...",16,122,1,0,"annelise heurtier, née en 1979 à villefranche-...","annelise heurtier, née en 1979 à villefranche-...",annelise heurtier née en 1979 à villefranchesu...,annelise heurtier née 1979 villefranchesursaôn...,"[annelise, heurtier, née, 1979, villefranchesu...",annelis heurti né 1979 villefranchesursaôn écr...
3,"Erik Orsenna, pseudonyme d’Éric Arnoult, est u...",21,125,2,0,"erik orsenna, pseudonyme d’éric arnoult, est u...","erik orsenna, pseudonyme d’éric arnoult, est u...",erik orsenna pseudonyme déric arnoult est un é...,erik orsenna pseudonyme déric arnoult écrivain...,"[erik, orsenna, pseudonyme, déric, arnoult, éc...",erik orsen pseudonym déric arnoult écrivain né...
4,Christophe Tison est un journaliste et écrivai...,13,77,0,0,christophe tison est un journaliste et écrivai...,christophe tison est un journaliste et écrivai...,christophe tison est un journaliste et écrivai...,christophe tison journaliste écrivain français...,"[christophe, tison, journaliste, écrivain, fra...",christoph tison journal écrivain franc né amie...
5,"Sylvain Prudhomme, né en 1979 à La Seyne-sur-M...",33,201,1,0,"sylvain prudhomme, né en 1979 à la seyne-sur-m...","sylvain prudhomme, né en 1979 à la seyne-sur-m...",sylvain prudhomme né en 1979 à la seynesurmer ...,sylvain prudhomme né 1979 seynesurmer écrivain...,"[sylvain, prudhomme, né, 1979, seynesurmer, éc...",sylvain prudhomm né 1979 seynesurm écrivain fr...
6,Sally Nicholls (née le 22 juin 1983 à Stockton...,19,121,2,0,sally nicholls (née le 22 juin 1983 à stockton...,sally nicholls (née le 22 juin 1983 à stockton...,sally nicholls née le 22 juin 1983 à stocktono...,sally nicholls née 22 juin 1983 stocktonontees...,"[sally, nicholls, née, 22, juin, 1983, stockto...",sally nicholl né 22 juin 1983 stocktononte ang...
7,"Maxime Drouot, connu sous les pseudonymes de M...",37,235,2,0,"maxime drouot, connu sous les pseudonymes de m...","maxime drouot, connu sous les pseudonymes de m...",maxime drouot connu sous les pseudonymes de ma...,maxime drouot connu sous les pseudonymes maxim...,"[maxime, drouot, connu, sous, les, pseudonymes...",maxim drouot connu sous le pseudonym maxim cha...
8,"Ivan Jablonka, né le 23 octobre 1973 à Paris, ...",21,147,2,0,"ivan jablonka, né le 23 octobre 1973 à paris, ...","ivan jablonka, né le 23 octobre 1973 à paris, ...",ivan jablonka né le 23 octobre 1973 à paris es...,ivan jablonka né 23 octobre 1973 paris histori...,"[ivan, jablonka, né, 23, octobre, 1973, paris,...",ivan jablonk né 23 octobr 1973 paris historien...
9,"Jean-Pierre Cabanes, né le 31 juillet 1949 à M...",15,93,2,0,"jean-pierre cabanes, né le 31 juillet 1949 à m...","jean-pierre cabanes, né le 31 juillet 1949 à m...",jeanpierre cabanes né le 31 juillet 1949 à mon...,jeanpierre cabanes né 31 juillet 1949 montpell...,"[jeanpierre, cabanes, né, 31, juillet, 1949, m...",jeanpierr caban né 31 juillet 1949 montpelli a...
10,Alain Ayroles est un scénariste de bande dessi...,16,91,2,0,alain ayroles est un scénariste de bande dessi...,alain ayroles est un scénariste de bande dessi...,alain ayroles est un scénariste de bande dessi...,alain ayroles scénariste bande dessinée né 26 ...,"[alain, ayroles, scénariste, bande, dessinée, ...",alain ayrol scénar band dessin né 26 janvi 196...
11,"Martha Wells, née le 1er septembre 1964 à Fort...",21,125,1,0,"martha wells, née le 1er septembre 1964 à fort...","martha wells, née le 1er septembre 1964 à fort...",martha wells née le 1er septembre 1964 à fort ...,martha wells née 1er septembre 1964 fort worth...,"[martha, wells, née, 1er, septembre, 1964, for...",marth wel né 1er septembr 1964 fort worth tex ...
12,"Amélie Nothomb /ameli nɔtɔ̃b/, nom de plume de...",129,832,3,0,"amélie nothomb /ameli nɔtɔ̃b/, nom de plume de...","amélie nothomb /ameli nɔtɔ̃b/, nom de plume de...",amélie nothomb ameli nɔtɔb nom de plume de fab...,amélie nothomb ameli nɔtɔb nom plume fabienne ...,"[amélie, nothomb, ameli, nɔtɔb, nom, plume, fa...",amel nothomb amel nɔtɔb nom plum fabien clair ...
13,Florence Hinckel est une autrice française de...,12,82,0,0,florence hinckel est une autrice française de...,florence hinckel est une autrice française de...,florence hinckel est une autrice française de...,florence hinckel autrice française romans enfa...,"[florence, hinckel, autrice, française, romans...",florenc hinckel autric français roman enfant a...
14,"Karine Tuil, née le 3 mai 1972 à Paris, est un...",13,69,2,0,"karine tuil, née le 3 mai 1972 à paris, est un...","karine tuil, née le 3 mai 1972 à paris, est un...",karine tuil née le 3 mai 1972 à paris est une ...,karine tuil née 3 mai 1972 paris romancière fr...,"[karine, tuil, née, 3, mai, 1972, paris, roman...",karin tuil né 3 mai 1972 paris romanci français
15,"Jérémie Kisling, né Jérémie Tschanz à Lausanne...",33,238,1,0,"jérémie kisling, né jérémie tschanz à lausanne...","jérémie kisling, né jérémie tschanz à lausanne...",jérémie kisling né jérémie tschanz à lausanne ...,jérémie kisling né jérémie tschanz lausanne 27...,"[jérémie, kisling, né, jérémie, tschanz, lausa...",jérem kisling né jérem tschanz lausann 27 févr...
16,"Née le 3 janvier 1969 à Bayonne, au Pays basqu...",122,730,4,1,"née le 3 janvier 1969 à bayonne, au pays basqu...","née le 3 janvier 1969 à bayonne, au pays basqu...",née le 3 janvier 1969 à bayonne au pays basque...,née 3 janvier 1969 bayonne pays basque marie d...,"[née, 3, janvier, 1969, bayonne, pays, basque,...",né 3 janvi 1969 bayon pay basqu mar darrieusse...
17,"Léonora Miano, née le 12 mars 1973 à Douala (C...",18,124,2,0,"léonora miano, née le 12 mars 1973 à douala (c...","léonora miano, née le 12 mars 1973 à douala (c...",léonora miano née le 12 mars 1973 à douala cam...,léonora miano née 12 mars 1973 douala cameroun...,"[léonora, miano, née, 12, mars, 1973, douala, ...",léonor miano né 12 mar 1973 doual cameroun fem...
18,"Ottessa Moshfegh, née en 20 mai 1981 à Boston ...",16,98,2,0,"ottessa moshfegh, née en 20 mai 1981 à boston ...","ottessa moshfegh, née en 20 mai 1981 à boston ...",ottessa moshfegh née en 20 mai 1981 à boston d...,ottessa moshfegh née 20 mai 1981 boston massac...,"[ottessa, moshfegh, née, 20, mai, 1981, boston...",ottess moshfegh né 20 mai 1981 boston massachu...
19,"David Lagercrantz, né le 4 septembre 1962 à So...",60,352,2,0,"david lagercrantz, né le 4 septembre 1962 à so...","david lagercrantz, né le 4 septembre 1962 à so...",david lagercrantz né le 4 septembre 1962 à sol...,david lagercrantz né 4 septembre 1962 solna jo...,"[david, lagercrantz, né, 4, septembre, 1962, s...",david lagercrantz né 4 septembr 1962 soln jour...
20,"Jonathan Coe, né le 19 août 1961 à Birmingham,...",13,75,2,0,"jonathan coe, né le 19 août 1961 à birmingham,...","jonathan coe, né le 19 août 1961 à birmingham,...",jonathan coe né le 19 août 1961 à birmingham e...,jonathan coe né 19 août 1961 birmingham écriva...,"[jonathan, coe, né, 19, août, 1961, birmingham...",jonathan co né 19 août 1961 birmingham écrivai...
21,"Dominique Forma, né en 1962 à Puteaux, est un ...",14,99,1,0,"dominique forma, né en 1962 à puteaux, est un ...","dominique forma, né en 1962 à puteaux, est un ...",dominique forma né en 1962 à puteaux est un sc...,dominique forma né 1962 puteaux scénariste réa...,"[dominique, forma, né, 1962, puteaux, scénaris...",domin form né 1962 puteau scénar réalis écriva...
22,"Margaret Eleanor « Peggy » Atwood, née le 18 n...",78,469,3,0,"margaret eleanor « peggy » atwood, née le 18 n...","margaret eleanor « peggy » atwood, née le 18 n...",margaret eleanor peggy atwood née le 18 nove...,margaret eleanor peggy atwood née 18 novembre ...,"[margaret, eleanor, peggy, atwood, née, 18, no...",margaret eleanor peggy atwood né 18 novembr 19...
23,"Marion Brunet, née en 1976 dans le Vaucluse, e...",25,150,1,0,"marion brunet, née en 1976 dans le vaucluse, e...","marion brunet, née en 1976 dans le vaucluse, e...",marion brunet née en 1976 dans le vaucluse est...,marion brunet née 1976 vaucluse femme lettres ...,"[marion, brunet, née, 1976, vaucluse, femme, l...",marion brunet né 1976 vauclus femm lettr franç...
24,"Cécile Coulon, née le 13 juin 1990 à Clermont-...",17,123,2,0,"cécile coulon, née le 13 juin 1990 à clermont-...","cécile coulon, née le 13 juin 1990 à clermont-...",cécile coulon née le 13 juin 1990 à clermontfe...,cécile coulon née 13 juin 1990 clermontferrand...,"[cécile, coulon, née, 13, juin, 1990, clermont...",cécil coulon né 13 juin 1990 clermontferrand p...
25,"Paolo Rumiz, né le 20 décembre 1947 à Trieste,...",17,98,2,0,"paolo rumiz, né le 20 décembre 1947 à trieste,...","paolo rumiz, né le 20 décembre 1947 à trieste,...",paolo rumiz né le 20 décembre 1947 à trieste e...,paolo rumiz né 20 décembre 1947 trieste journa...,"[paolo, rumiz, né, 20, décembre, 1947, trieste...",paolo rumiz né 20 décembr 1947 triest journal ...
26,"Éléonore Pourriat est une actrice, scénariste ...",9,72,0,0,"éléonore pourriat est une actrice, scénariste ...","éléonore pourriat est une actrice, scénariste ...",éléonore pourriat est une actrice scénariste e...,éléonore pourriat actrice scénariste réalisatr...,"[éléonore, pourriat, actrice, scénariste, réal...",éléonor pourriat actric scénar réalis français
27,"Jean-Paul Dubois, né le 20 février 1950 à Toul...",13,77,2,0,"jean-paul dubois, né le 20 février 1950 à toul...","jean-paul dubois, né le 20 février 1950 à toul...",jeanpaul dubois né le 20 février 1950 à toulou...,jeanpaul dubois né 20 février 1950 toulouse éc...,"[jeanpaul, dubois, né, 20, février, 1950, toul...",jeanpaul dubois né 20 févri 1950 toulous écriv...
28,"Jean-Baptiste Andrea, né le 4 avril 1971 à Sai...",17,119,2,0,"jean-baptiste andrea, né le 4 avril 1971 à sai...","jean-baptiste andrea, né le 4 avril 1971 à sai...",jeanbaptiste andrea né le 4 avril 1971 à saint...,jeanbaptiste andrea né 4 avril 1971 saintgerma...,"[jeanbaptiste, andrea, né, 4, avril, 1971, sai...",jeanbapt andre né 4 avril 1971 saintgermainenl...
29,Christophe Tison est un journaliste et écrivai...,13,77,0,0,christophe tison est un journaliste et écrivai...,christophe tison est un journaliste et écrivai...,christophe tison est un journaliste et écrivai...,christophe tison journaliste écrivain français...,"[christophe, tison, journaliste, écrivain, fra...",christoph tison journal écrivain franc né amie...
...,...,...,...,...,...,...,...,...,...,...,...
109,Jean Anouilh (/a.nuj/) est un écrivain et dram...,307,1863,5,0,jean anouilh (/a.nuj/) est un écrivain et dram...,jean anouilh (/a.nuj/) est un écrivain et dram...,jean anouilh anuj est un écrivain et dramaturg...,jean anouilh anuj écrivain dramaturge français...,"[jean, anouilh, anuj, écrivain, dramaturge, fr...",jean anouilh anuj écrivain dramaturg franc né ...
110,"Pierre Ambroise Choderlos de Laclos, né à Amie...",53,311,3,0,"pierre ambroise choderlos de laclos, né à amie...","pierre ambroise choderlos de laclos, né à amie...",pierre ambroise choderlos de laclos né à amien...,pierre ambroise choderlos laclos né amiens 18 ...,"[pierre, ambroise, choderlos, laclos, né, amie...",pierr ambrois choderlos laclos né amien 18 oct...
111,"Victor Hugo est un poète, dramaturge, écrivain...",409,2497,6,2,"victor hugo est un poète, dramaturge, écrivain...","victor hugo est un poète, dramaturge, écrivain...",victor hugo est un poète dramaturge écrivain r...,victor hugo poète dramaturge écrivain romancie...,"[victor, hugo, poète, dramaturge, écrivain, ro...",victor hugo poet dramaturg écrivain romanci de...
112,Anna Gavalda est une femme de lettres français...,15,95,2,0,anna gavalda est une femme de lettres français...,anna gavalda est une femme de lettres français...,anna gavalda est une femme de lettres français...,anna gavalda femme lettres française née 9 déc...,"[anna, gavalda, femme, lettres, française, née...",anna gavald femm lettr français né 9 décembr 1...
113,"Marie-Madeleine Pioche de La Vergne, comtesse ...",34,183,4,0,"marie-madeleine pioche de la vergne, comtesse ...","marie-madeleine pioche de la vergne, comtesse ...",mariemadeleine pioche de la vergne comtesse de...,mariemadeleine pioche vergne comtesse fayette ...,"[mariemadeleine, pioche, vergne, comtesse, fay...",mariemadelein pioch vergn comtess fayet lafaye...
114,Émile Zola est un écrivain et journaliste fran...,176,1071,3,0,émile zola est un écrivain et journaliste fran...,émile zola est un écrivain et journaliste fran...,émile zola est un écrivain et journaliste fran...,émile zola écrivain journaliste français né 2 ...,"[émile, zola, écrivain, journaliste, français,...",émil zol écrivain journal franc né 2 avril 184...
115,"Jean-Baptiste Poquelin, dit Molière, est un co...",434,2711,5,1,"jean-baptiste poquelin, dit molière, est un co...","jean-baptiste poquelin, dit molière, est un co...",jeanbaptiste poquelin dit molière est un coméd...,jeanbaptiste poquelin dit molière comédien dra...,"[jeanbaptiste, poquelin, dit, molière, comédie...",jeanbapt poquelin dit moli comédien dramaturg ...
116,Alexandre Dumas (dit aussi Alexandre Dumas pèr...,267,1674,4,1,alexandre dumas (dit aussi alexandre dumas pèr...,alexandre dumas (dit aussi alexandre dumas pèr...,alexandre dumas dit aussi alexandre dumas père...,alexandre dumas dit aussi alexandre dumas père...,"[alexandre, dumas, dit, aussi, alexandre, duma...",alexandr dum dit auss alexandr dum per écrivai...
117,Gilles Legardinier est un écrivain et scénaris...,24,142,2,0,gilles legardinier est un écrivain et scénaris...,gilles legardinier est un écrivain et scénaris...,gilles legardinier est un écrivain et scénaris...,gilles legardinier écrivain scénariste françai...,"[gilles, legardinier, écrivain, scénariste, fr...",gill legardini écrivain scénar franc né 27 oct...
118,"Edmond Rostand, né le 1er avril 1868 à Marseil...",62,373,3,0,"edmond rostand, né le 1er avril 1868 à marseil...","edmond rostand, né le 1er avril 1868 à marseil...",edmond rostand né le 1er avril 1868 à marseill...,edmond rostand né 1er avril 1868 marseille mor...,"[edmond, rostand, né, 1er, avril, 1868, marsei...",edmond rostand né 1er avril 1868 marseil mort ...
119,Ernest Miller Hemingway [ˈɝnɪst ˈmɪlɚ ˈhɛmɪŋˌw...,483,2838,8,1,ernest miller hemingway [ˈɝnɪst ˈmɪlɚ ˈhɛmɪŋˌw...,ernest miller hemingway [ˈɝnɪst ˈmɪlɚ ˈhɛmɪŋˌw...,ernest miller hemingway ˈɝnɪst ˈmɪlɚ ˈhɛmɪŋˌwe...,ernest miller hemingway ˈɝnɪst ˈmɪlɚ ˈhɛmɪŋˌwe...,"[ernest, miller, hemingway, ˈɝnɪst, ˈmɪlɚ, ˈhɛ...",ernest mill hemingway ˈɝnɪst ˈmɪlɚ ˈhɛmɪŋˌweɪ ...
120,"Guillaume Musso, né le 6 juin 1974 à Antibes, ...",13,72,2,0,"guillaume musso, né le 6 juin 1974 à antibes, ...","guillaume musso, né le 6 juin 1974 à antibes, ...",guillaume musso né le 6 juin 1974 à antibes es...,guillaume musso né 6 juin 1974 antibes romanci...,"[guillaume, musso, né, 6, juin, 1974, antibes,...",guillaum musso né 6 juin 1974 antib romanci franc
121,"Edgar Allan Poe [ˈɛdɡɚ ˈælən poʊ], né le 19 ja...",539,3273,7,0,"edgar allan poe [ˈɛdɡɚ ˈælən poʊ], né le 19 ja...","edgar allan poe [ˈɛdɡɚ ˈælən poʊ], né le 19 ja...",edgar allan poe ˈɛdɡɚ ˈælən poʊ né le 19 janvi...,edgar allan poe ˈɛdɡɚ ˈælən poʊ né 19 janvier ...,"[edgar, allan, poe, ˈɛdɡɚ, ˈælən, poʊ, né, 19,...",edgar allan po ˈɛdɡɚ ˈælən poʊ né 19 janvi 180...
122,"Jonas Jonasson, né le 6 juillet 1961 à Växjö, ...",39,214,2,0,"jonas jonasson, né le 6 juillet 1961 à växjö, ...","jonas jonasson, né le 6 juillet 1961 à växjö, ...",jonas jonasson né le 6 juillet 1961 à växjö es...,jonas jonasson né 6 juillet 1961 växjö écrivai...,"[jonas, jonasson, né, 6, juillet, 1961, växjö,...",jon jonasson né 6 juillet 1961 växjö écrivain ...
123,"Guillaume Musso, né le 6 juin 1974 à Antibes, ...",13,72,2,0,"guillaume musso, né le 6 juin 1974 à antibes, ...","guillaume musso, né le 6 juin 1974 à antibes, ...",guillaume musso né le 6 juin 1974 à antibes es...,guillaume musso né 6 juin 1974 antibes romanci...,"[guillaume, musso, né, 6, juin, 1974, antibes,...",guillaum musso né 6 juin 1974 antib romanci franc
124,"Jean Edith Camilla Läckberg Eriksson, née le 3...",92,550,2,0,"jean edith camilla läckberg eriksson, née le 3...","jean edith camilla läckberg eriksson, née le 3...",jean edith camilla läckberg eriksson née le 30...,jean edith camilla läckberg eriksson née 30 ao...,"[jean, edith, camilla, läckberg, eriksson, née...",jean edith camill läckberg eriksson né 30 août...
125,Arthur Conan Doyle (né Arthur Ignatius Conan D...,127,740,5,1,arthur conan doyle (né arthur ignatius conan d...,arthur conan doyle (né arthur ignatius conan d...,arthur conan doyle né arthur ignatius conan do...,arthur conan doyle né arthur ignatius conan do...,"[arthur, conan, doyle, né, arthur, ignatius, c...",arthur conan doyl né arthur ignatius conan doy...
126,"William Shakespeare, baptisé le 26 avril 1564 ...",249,1615,8,0,"william shakespeare, baptisé le 26 avril 1564 ...","william shakespeare, baptisé le 26 avril 1564 ...",william shakespeare baptisé le 26 avril 1564 à...,william shakespeare baptisé 26 avril 1564 stra...,"[william, shakespeare, baptisé, 26, avril, 156...",william shakespear baptis 26 avril 1564 stratf...
127,"Jean-Baptiste Poquelin, dit Molière, est un co...",434,2711,5,1,"jean-baptiste poquelin, dit molière, est un co...","jean-baptiste poquelin, dit molière, est un co...",jeanbaptiste poquelin dit molière est un coméd...,jeanbaptiste poquelin dit molière comédien dra...,"[jeanbaptiste, poquelin, dit, molière, comédie...",jeanbapt poquelin dit moli comédien dramaturg ...
128,"Pierre Corneille, aussi appelé « le Grand Corn...",805,4790,10,5,"pierre corneille, aussi appelé « le grand corn...","pierre corneille, aussi appelé « le grand corn...",pierre corneille aussi appelé le grand cornei...,pierre corneille aussi appelé grand corneille ...,"[pierre, corneille, aussi, appelé, grand, corn...",pierr corneil auss appel grand corneil corneil...
129,"Veronica Anne Roth, née le 19 août 1988 à New ...",102,635,7,0,"veronica anne roth, née le 19 août 1988 à new ...","veronica anne roth, née le 19 août 1988 à new ...",veronica anne roth née le 19 août 1988 à new y...,veronica anne roth née 19 août 1988 new york p...,"[veronica, anne, roth, née, 19, août, 1988, ne...",veronic anne roth né 19 août 1988 new york par...
130,Anna Gavalda est une femme de lettres français...,15,95,2,0,anna gavalda est une femme de lettres français...,anna gavalda est une femme de lettres français...,anna gavalda est une femme de lettres français...,anna gavalda femme lettres française née 9 déc...,"[anna, gavalda, femme, lettres, française, née...",anna gavald femm lettr français né 9 décembr 1...
131,Marguerite Duras — nom de plume de Marguerite ...,343,2098,7,1,marguerite duras — nom de plume de marguerite ...,marguerite duras — nom de plume de marguerite ...,marguerite duras nom de plume de marguerite d...,marguerite duras nom plume marguerite donnadie...,"[marguerite, duras, nom, plume, marguerite, do...",marguerit dur nom plum marguerit donnadieu fem...

## Advanced text processing

### N-grams

In [18]:
from nltk.util import ngrams

**Tips :** Use `tokenized` column

0      [(paolo, rumiz), (rumiz, né), (né, 20), (20, d...
1      [(saverio, tomasella), (tomasella, psychanalys...
2      [(annelise, heurtier), (heurtier, née), (née, ...
3      [(erik, orsenna), (orsenna, pseudonyme), (pseu...
4      [(christophe, tison), (tison, journaliste), (j...
5      [(sylvain, prudhomme), (prudhomme, né), (né, 1...
6      [(sally, nicholls), (nicholls, née), (née, 22)...
7      [(maxime, drouot), (drouot, connu), (connu, so...
8      [(ivan, jablonka), (jablonka, né), (né, 23), (...
9      [(jeanpierre, cabanes), (cabanes, né), (né, 31...
10     [(alain, ayroles), (ayroles, scénariste), (scé...
11     [(martha, wells), (wells, née), (née, 1er), (1...
12     [(amélie, nothomb), (nothomb, ameli), (ameli, ...
13     [(florence, hinckel), (hinckel, autrice), (aut...
14     [(karine, tuil), (tuil, née), (née, 3), (3, ma...
15     [(jérémie, kisling), (kisling, né), (né, jérém...
16     [(née, 3), (3, janvier), (janvier, 1969), (196...
17     [(léonora, miano), (miano, née), (née, 12), (1...
18     [(ottessa, moshfegh), (moshfegh, née), (née, 2...
19     [(david, lagercrantz), (lagercrantz, né), (né,...
20     [(jonathan, coe), (coe, né), (né, 19), (19, ao...
21     [(dominique, forma), (forma, né), (né, 1962), ...
22     [(margaret, eleanor), (eleanor, peggy), (peggy...
23     [(marion, brunet), (brunet, née), (née, 1976),...
24     [(cécile, coulon), (coulon, née), (née, 13), (...
25     [(paolo, rumiz), (rumiz, né), (né, 20), (20, d...
26     [(éléonore, pourriat), (pourriat, actrice), (a...
27     [(jeanpaul, dubois), (dubois, né), (né, 20), (...
28     [(jeanbaptiste, andrea), (andrea, né), (né, 4)...
29     [(christophe, tison), (tison, journaliste), (j...
                             ...
109    [(jean, anouilh), (anouilh, anuj), (anuj, écri...
110    [(pierre, ambroise), (ambroise, choderlos), (c...
111    [(victor, hugo), (hugo, poète), (poète, dramat...
112    [(anna, gavalda), (gavalda, femme), (femme, le...
113    [(mariemadeleine, pioche), (pioche, vergne), (...
114    [(émile, zola), (zola, écrivain), (écrivain, j...
115    [(jeanbaptiste, poquelin), (poquelin, dit), (d...
116    [(alexandre, dumas), (dumas, dit), (dit, aussi...
117    [(gilles, legardinier), (legardinier, écrivain...
118    [(edmond, rostand), (rostand, né), (né, 1er), ...
119    [(ernest, miller), (miller, hemingway), (hemin...
120    [(guillaume, musso), (musso, né), (né, 6), (6,...
121    [(edgar, allan), (allan, poe), (poe, ˈɛdɡɚ), (...
122    [(jonas, jonasson), (jonasson, né), (né, 6), (...
123    [(guillaume, musso), (musso, né), (né, 6), (6,...
124    [(jean, edith), (edith, camilla), (camilla, lä...
125    [(arthur, conan), (conan, doyle), (doyle, né),...
126    [(william, shakespeare), (shakespeare, baptisé...
127    [(jeanbaptiste, poquelin), (poquelin, dit), (d...
128    [(pierre, corneille), (corneille, aussi), (aus...
129    [(veronica, anne), (anne, roth), (roth, née), ...
130    [(anna, gavalda), (gavalda, femme), (femme, le...
131    [(marguerite, duras), (duras, nom), (nom, plum...
132    [(paula, hawkins), (hawkins, née), (née, 26), ...
133    [(salinger, nom), (nom, plume), (plume, jerome...
134    [(gaston, leroux), (leroux, romancier), (roman...
135    [(philip, pullman), (pullman, né), (né, 19), (...
136    [(ken, follett), (follett, né), (né, 5), (5, j...
137    [(émile, zola), (zola, écrivain), (écrivain, j...
138    [(honoré, balzac), (balzac, né), (né, honoré),...
Name: n-grams, Length: 139, dtype: object

### Term Frequency (TF)

In [20]:
tokenized_description = data[data['wordCount'] == 409]['tokenized'][63]

In [21]:
tokenized_description

['victor',
 'hugo',
 'poète',
 'dramaturge',
 'écrivain',
 'romancier',
 'dessinateur',
 'romantique',
 'français',
 'né',
 '26',
 'février',
 '1802',
 '7',
 'ventôse',
 'an',
 'x',
 'selon',
 'calendrier',
 'républicain',
 'encore',
 'vigueur',
 'besançon',
 'mort',
 '22',
 'mai',
 '1885',
 'paris',
 'considéré',
 'comme',
 'lun',
 'plus',
 'importants',
 'écrivains',
 'langue',
 'française',
 'aussi',
 'personnalité',
 'politique',
 'intellectuel',
 'engagé',
 'a',
 'rôle',
 'idéologique',
 'majeur',
 'occupe',
 'place',
 'marquante',
 'lhistoire',
 'lettres',
 'françaises',
 'xixe',
 'siècle',
 'genres',
 'domaines',
 'dune',
 'remarquable',
 'variété',
 'théâtre',
 'victor',
 'hugo',
 'manifeste',
 'comme',
 'chefs',
 'file',
 'romantisme',
 'français',
 'lorsquil',
 'expose',
 'théorie',
 'drame',
 'romantique',
 'les',
 'préfaces',
 'introduisent',
 'cromwell',
 '1827',
 'puis',
 'hernani',
 '1830',
 'véritables',
 'manifestes',
 'puis',
 'autres',
 'œuvres',
 'dramatiques',
 'ruy',
 'blas',
 '1838',
 'aussi',
 'lucrèce',
 'borgia',
 'roi',
 'samuse',
 'victor',
 'hugo',
 'aussi',
 'poète',
 'lyrique',
 'recueils',
 'comme',
 'odes',
 'ballades',
 '1826',
 'les',
 'feuilles',
 'dautomne',
 '1831',
 'les',
 'contemplations',
 '1856',
 'aussi',
 'poète',
 'engagé',
 'contre',
 'napoléon',
 'iii',
 'les',
 'châtiments',
 '1853',
 'encore',
 'poète',
 'épique',
 'légende',
 'siècles',
 '1859',
 '1877',
 'romans',
 'rencontrent',
 'également',
 'grand',
 'succès',
 'populaire',
 'notamment',
 'notredame',
 'paris',
 '1831',
 'plus',
 'encore',
 'les',
 'misérables',
 '1862',
 'œuvre',
 'multiple',
 'comprend',
 'aussi',
 'discours',
 'politiques',
 'chambre',
 'pairs',
 'lassemblée',
 'constituante',
 'lassemblée',
 'législative',
 'notamment',
 'peine',
 'mort',
 'lécole',
 'leurope',
 'récits',
 'voyages',
 'rhin',
 '1842',
 'choses',
 'vues',
 'posthumes',
 '1887',
 '1890',
 'correspondance',
 'abondante',
 'ainsi',
 'nombreux',
 'croquis',
 'dessins',
 'plume',
 'lavis',
 'victor',
 'hugo',
 'a',
 'fortement',
 'contribué',
 'renouvellement',
 'poésie',
 'théâtre',
 'a',
 'admiré',
 'contemporains',
 'lest',
 'encore',
 'a',
 'aussi',
 'contesté',
 'certains',
 'auteurs',
 'modernes',
 'a',
 'permis',
 'nombreuses',
 'générations',
 'développer',
 'réflexion',
 'lengagement',
 'lécrivain',
 'vie',
 'politique',
 'sociale',
 'grâce',
 'multiples',
 'prises',
 'position',
 'choisissant',
 'sexiler',
 'vivre',
 'guernesey',
 'pendant',
 'les',
 'vingt',
 'ans',
 'second',
 'empire',
 'choix',
 'fois',
 'moraux',
 'politiques',
 'durant',
 'deuxième',
 'partie',
 'vie',
 'œuvre',
 'hors',
 'commun',
 'fait',
 'personnage',
 'emblématique',
 'troisième',
 'république',
 'a',
 'honoré',
 'funérailles',
 'nationales',
 'accompagné',
 'transfert',
 'dépouille',
 'panthéon',
 'paris',
 '1er',
 'juin',
 '1885',
 'dix',
 'jours',
 'après',
 'mort']

**Tips :** 
- Build a dictionnay `{word:count, word1:count1, ...}` 

- **/!\\** take care to not override already existing keys

{'1802': 1,
 '1826': 1,
 '1827': 1,
 '1830': 1,
 '1831': 2,
 '1838': 1,
 '1842': 1,
 '1853': 1,
 '1856': 1,
 '1859': 1,
 '1862': 1,
 '1877': 1,
 '1885': 2,
 '1887': 1,
 '1890': 1,
 '1er': 1,
 '22': 1,
 '26': 1,
 '7': 1,
 'a': 6,
 'abondante': 1,
 'accompagné': 1,
 'admiré': 1,
 'ainsi': 1,
 'an': 1,
 'ans': 1,
 'après': 1,
 'aussi': 6,
 'auteurs': 1,
 'autres': 1,
 'ballades': 1,
 'besançon': 1,
 'blas': 1,
 'borgia': 1,
 'calendrier': 1,
 'certains': 1,
 'chambre': 1,
 'chefs': 1,
 'choisissant': 1,
 'choix': 1,
 'choses': 1,
 'châtiments': 1,
 'comme': 3,
 'commun': 1,
 'comprend': 1,
 'considéré': 1,
 'constituante': 1,
 'contemplations': 1,
 'contemporains': 1,
 'contesté': 1,
 'contre': 1,
 'contribué': 1,
 'correspondance': 1,
 'cromwell': 1,
 'croquis': 1,
 'dautomne': 1,
 'dessinateur': 1,
 'dessins': 1,
 'deuxième': 1,
 'discours': 1,
 'dix': 1,
 'domaines': 1,
 'dramatiques': 1,
 'dramaturge': 1,
 'drame': 1,
 'dune': 1,
 'durant': 1,
 'dépouille': 1,
 'développer': 1,
 'emblématique': 1,
 'empire': 1,
 'encore': 4,
 'engagé': 2,
 'expose': 1,
 'fait': 1,
 'feuilles': 1,
 'file': 1,
 'fois': 1,
 'fortement': 1,
 'français': 2,
 'française': 1,
 'françaises': 1,
 'funérailles': 1,
 'février': 1,
 'genres': 1,
 'grand': 1,
 'grâce': 1,
 'guernesey': 1,
 'générations': 1,
 'hernani': 1,
 'honoré': 1,
 'hors': 1,
 'hugo': 4,
 'idéologique': 1,
 'iii': 1,
 'importants': 1,
 'intellectuel': 1,
 'introduisent': 1,
 'jours': 1,
 'juin': 1,
 'langue': 1,
 'lassemblée': 2,
 'lavis': 1,
 'lengagement': 1,
 'les': 6,
 'lest': 1,
 'lettres': 1,
 'leurope': 1,
 'lhistoire': 1,
 'lorsquil': 1,
 'lucrèce': 1,
 'lun': 1,
 'lyrique': 1,
 'lécole': 1,
 'lécrivain': 1,
 'légende': 1,
 'législative': 1,
 'mai': 1,
 'majeur': 1,
 'manifeste': 1,
 'manifestes': 1,
 'marquante': 1,
 'misérables': 1,
 'modernes': 1,
 'moraux': 1,
 'mort': 3,
 'multiple': 1,
 'multiples': 1,
 'napoléon': 1,
 'nationales': 1,
 'nombreuses': 1,
 'nombreux': 1,
 'notamment': 2,
 'notredame': 1,
 'né': 1,
 'occupe': 1,
 'odes': 1,
 'pairs': 1,
 'panthéon': 1,
 'paris': 3,
 'partie': 1,
 'peine': 1,
 'pendant': 1,
 'permis': 1,
 'personnage': 1,
 'personnalité': 1,
 'place': 1,
 'plume': 1,
 'plus': 2,
 'politique': 2,
 'politiques': 2,
 'populaire': 1,
 'position': 1,
 'posthumes': 1,
 'poète': 4,
 'poésie': 1,
 'prises': 1,
 'préfaces': 1,
 'puis': 2,
 'recueils': 1,
 'remarquable': 1,
 'rencontrent': 1,
 'renouvellement': 1,
 'rhin': 1,
 'roi': 1,
 'romancier': 1,
 'romans': 1,
 'romantique': 2,
 'romantisme': 1,
 'ruy': 1,
 'récits': 1,
 'réflexion': 1,
 'républicain': 1,
 'république': 1,
 'rôle': 1,
 'samuse': 1,
 'second': 1,
 'selon': 1,
 'sexiler': 1,
 'siècle': 1,
 'siècles': 1,
 'sociale': 1,
 'succès': 1,
 'théorie': 1,
 'théâtre': 2,
 'transfert': 1,
 'troisième': 1,
 'variété': 1,
 'ventôse': 1,
 'victor': 4,
 'vie': 2,
 'vigueur': 1,
 'vingt': 1,
 'vivre': 1,
 'voyages': 1,
 'vues': 1,
 'véritables': 1,
 'x': 1,
 'xixe': 1,
 'écrivain': 1,
 'écrivains': 1,
 'également': 1,
 'épique': 1,
 'œuvre': 2,
 'œuvres': 1}

In [23]:
advanced_processing_df = pd.DataFrame.from_dict(
    words, orient='index', columns=['wordCount']).reset_index()
advanced_processing_df.columns = ['word', 'wordCount']
advanced_processing_df

             word  wordCount
0          victor          4
1            hugo          4
2           poète          4
3      dramaturge          1
4        écrivain          1
5       romancier          1
6     dessinateur          1
7      romantique          2
8        français          2
9              né          1
10             26          1
11        février          1
12           1802          1
13              7          1
14        ventôse          1
15             an          1
16              x          1
17          selon          1
18     calendrier          1
19    républicain          1
20         encore          4
21        vigueur          1
22       besançon          1
23           mort          3
24             22          1
25            mai          1
26           1885          2
27          paris          3
28      considéré          1
29          comme          3
..            ...        ...
175       pendant          1
176         vingt          1
177           ans          1
178        second          1
179        empire          1
180         choix          1
181          fois          1
182        moraux          1
183        durant          1
184      deuxième          1
185        partie          1
186          hors          1
187        commun          1
188          fait          1
189    personnage          1
190  emblématique          1
191     troisième          1
192    république          1
193        honoré          1
194   funérailles          1
195    nationales          1
196    accompagné          1
197     transfert          1
198     dépouille          1
199      panthéon          1
200           1er          1
201          juin          1
202           dix          1
203         jours          1
204         après          1

[205 rows x 2 columns]

**Tips :** use `advanced_processing_df`

**Reminder :** Term Frequency is `wordCount` divided by total number of words

             word  wordCount        tf
0          victor          4  0.019512
1            hugo          4  0.019512
2           poète          4  0.019512
3      dramaturge          1  0.004878
4        écrivain          1  0.004878
5       romancier          1  0.004878
6     dessinateur          1  0.004878
7      romantique          2  0.009756
8        français          2  0.009756
9              né          1  0.004878
10             26          1  0.004878
11        février          1  0.004878
12           1802          1  0.004878
13              7          1  0.004878
14        ventôse          1  0.004878
15             an          1  0.004878
16              x          1  0.004878
17          selon          1  0.004878
18     calendrier          1  0.004878
19    républicain          1  0.004878
20         encore          4  0.019512
21        vigueur          1  0.004878
22       besançon          1  0.004878
23           mort          3  0.014634
24             22          1  0.004878
25            mai          1  0.004878
26           1885          2  0.009756
27          paris          3  0.014634
28      considéré          1  0.004878
29          comme          3  0.014634
..            ...        ...       ...
175       pendant          1  0.004878
176         vingt          1  0.004878
177           ans          1  0.004878
178        second          1  0.004878
179        empire          1  0.004878
180         choix          1  0.004878
181          fois          1  0.004878
182        moraux          1  0.004878
183        durant          1  0.004878
184      deuxième          1  0.004878
185        partie          1  0.004878
186          hors          1  0.004878
187        commun          1  0.004878
188          fait          1  0.004878
189    personnage          1  0.004878
190  emblématique          1  0.004878
191     troisième          1  0.004878
192    république          1  0.004878
193        honoré          1  0.004878
194   funérailles          1  0.004878
195    nationales          1  0.004878
196    accompagné          1  0.004878
197     transfert          1  0.004878
198     dépouille          1  0.004878
199      panthéon          1  0.004878
200           1er          1  0.004878
201          juin          1  0.004878
202           dix          1  0.004878
203         jours          1  0.004878
204         après          1  0.004878

[205 rows x 3 columns]

### Inverse Document Frequency (IDF)

**Reminder :** IDF (**I**nverse **D**ocument **F**requency) is 1 divided by number of row in `data` that contains the word you want to calculate IDF score.

             word  wordCount        tf       idf
0          victor          4  0.019512  0.250000
1            hugo          4  0.019512  0.090909
2           poète          4  0.019512  0.100000
3      dramaturge          1  0.004878  0.058824
4        écrivain          1  0.004878  0.011628
5       romancier          1  0.004878  0.041667
6     dessinateur          1  0.004878  0.500000
7      romantique          2  0.009756  0.200000
8        français          2  0.009756  0.011111
9              né          1  0.004878  0.007353
10             26          1  0.004878  0.111111
11        février          1  0.004878  0.066667
12           1802          1  0.004878  0.333333
13              7          1  0.004878  0.012048
14        ventôse          1  0.004878  0.500000
15             an          1  0.004878  0.007353
16              x          1  0.004878  0.012821
17          selon          1  0.004878  0.200000
18     calendrier          1  0.004878  0.166667
19    républicain          1  0.004878  0.250000
20         encore          4  0.019512  0.076923
21        vigueur          1  0.004878  0.333333
22       besançon          1  0.004878  0.500000
23           mort          3  0.014634  0.018182
24             22          1  0.004878  0.052632
25            mai          1  0.004878  0.028571
26           1885          2  0.009756  0.200000
27          paris          3  0.014634  0.026316
28      considéré          1  0.004878  0.062500
29          comme          3  0.014634  0.025000
..            ...        ...       ...       ...
175       pendant          1  0.004878  0.050000
176         vingt          1  0.004878  0.055556
177           ans          1  0.004878  0.015873
178        second          1  0.004878  0.047619
179        empire          1  0.004878  0.142857
180         choix          1  0.004878  0.250000
181          fois          1  0.004878  0.037037
182        moraux          1  0.004878  0.200000
183        durant          1  0.004878  0.166667
184      deuxième          1  0.004878  0.200000
185        partie          1  0.004878  0.055556
186          hors          1  0.004878  0.333333
187        commun          1  0.004878  0.111111
188          fait          1  0.004878  0.043478
189    personnage          1  0.004878  0.047619
190  emblématique          1  0.004878  0.166667
191     troisième          1  0.004878  0.200000
192    république          1  0.004878  0.250000
193        honoré          1  0.004878  0.200000
194   funérailles          1  0.004878  0.500000
195    nationales          1  0.004878  0.500000
196    accompagné          1  0.004878  0.166667
197     transfert          1  0.004878  0.500000
198     dépouille          1  0.004878  0.500000
199      panthéon          1  0.004878  0.333333
200           1er          1  0.004878  0.090909
201          juin          1  0.004878  0.050000
202           dix          1  0.004878  0.142857
203         jours          1  0.004878  0.200000
204         après          1  0.004878  0.034483

[205 rows x 4 columns]

### TF-IDF

**Reminder :** TF-IDF formula is ```tf * idf```

             word  wordCount        tf       idf    tf-idf
0          victor          4  0.019512  0.250000  0.004878
1            hugo          4  0.019512  0.090909  0.001774
2           poète          4  0.019512  0.100000  0.001951
3      dramaturge          1  0.004878  0.058824  0.000287
4        écrivain          1  0.004878  0.011628  0.000057
5       romancier          1  0.004878  0.041667  0.000203
6     dessinateur          1  0.004878  0.500000  0.002439
7      romantique          2  0.009756  0.200000  0.001951
8        français          2  0.009756  0.011111  0.000108
9              né          1  0.004878  0.007353  0.000036
10             26          1  0.004878  0.111111  0.000542
11        février          1  0.004878  0.066667  0.000325
12           1802          1  0.004878  0.333333  0.001626
13              7          1  0.004878  0.012048  0.000059
14        ventôse          1  0.004878  0.500000  0.002439
15             an          1  0.004878  0.007353  0.000036
16              x          1  0.004878  0.012821  0.000063
17          selon          1  0.004878  0.200000  0.000976
18     calendrier          1  0.004878  0.166667  0.000813
19    républicain          1  0.004878  0.250000  0.001220
20         encore          4  0.019512  0.076923  0.001501
21        vigueur          1  0.004878  0.333333  0.001626
22       besançon          1  0.004878  0.500000  0.002439
23           mort          3  0.014634  0.018182  0.000266
24             22          1  0.004878  0.052632  0.000257
25            mai          1  0.004878  0.028571  0.000139
26           1885          2  0.009756  0.200000  0.001951
27          paris          3  0.014634  0.026316  0.000385
28      considéré          1  0.004878  0.062500  0.000305
29          comme          3  0.014634  0.025000  0.000366
..            ...        ...       ...       ...       ...
175       pendant          1  0.004878  0.050000  0.000244
176         vingt          1  0.004878  0.055556  0.000271
177           ans          1  0.004878  0.015873  0.000077
178        second          1  0.004878  0.047619  0.000232
179        empire          1  0.004878  0.142857  0.000697
180         choix          1  0.004878  0.250000  0.001220
181          fois          1  0.004878  0.037037  0.000181
182        moraux          1  0.004878  0.200000  0.000976
183        durant          1  0.004878  0.166667  0.000813
184      deuxième          1  0.004878  0.200000  0.000976
185        partie          1  0.004878  0.055556  0.000271
186          hors          1  0.004878  0.333333  0.001626
187        commun          1  0.004878  0.111111  0.000542
188          fait          1  0.004878  0.043478  0.000212
189    personnage          1  0.004878  0.047619  0.000232
190  emblématique          1  0.004878  0.166667  0.000813
191     troisième          1  0.004878  0.200000  0.000976
192    république          1  0.004878  0.250000  0.001220
193        honoré          1  0.004878  0.200000  0.000976
194   funérailles          1  0.004878  0.500000  0.002439
195    nationales          1  0.004878  0.500000  0.002439
196    accompagné          1  0.004878  0.166667  0.000813
197     transfert          1  0.004878  0.500000  0.002439
198     dépouille          1  0.004878  0.500000  0.002439
199      panthéon          1  0.004878  0.333333  0.001626
200           1er          1  0.004878  0.090909  0.000443
201          juin          1  0.004878  0.050000  0.000244
202           dix          1  0.004878  0.142857  0.000697
203         jours          1  0.004878  0.200000  0.000976
204         après          1  0.004878  0.034483  0.000168

[205 rows x 5 columns]

### Bag of words

In [28]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [29]:
descriptions = data['withoutStopwords'].values.tolist()

**Tips :** Use cv method to fit and transform cv on description to get countVectorizer result

In [30]:
trained_cv =

In [31]:
pd.DataFrame(trained_cv.A, columns=cv.vocabulary_)

,paolo,rumiz,né,20,décembre,1947,trieste,journaliste,écrivain,voyageur,...,empreints,philip,pullman,norwich,norfolk,ken,follett,cardiff,gallois,despionnage
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
24,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
110,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
111,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
112,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
113,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
114,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
115,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
116,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
117,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
118,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
119,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
120,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
121,0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
122,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
123,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
124,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
125,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
126,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
127,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
128,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
129,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
130,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
131,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
132,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
133,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
134,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
135,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
136,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
137,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
138,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0